// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/proto/apiproxy/apiproxy.proto

package apiproxyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxResumeService_ResumeSandbox_FullMethodName = "/agentenv.apiproxy.v1.SandboxResumeService/ResumeSandbox"
)

// SandboxResumeServiceClient is the client API for SandboxResumeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The one thing the data plane asks the control plane for.
//
// 🔴 **One RPC, and it stays one RPC.** The gateway is a router: it resolves a
// sandbox to a node and forwards bytes. The only question it cannot answer from
// its own projection is "this sandbox is paused — wake it", and that is a
// decision, so it belongs to the API half. Everything else the gateway needs it
// already has. A second method here would be the beginning of the gateway
// asking the control plane to decide things on the request path, which is the
// arrangement this split exists to end.
//
// 🔴 **A separate file from `scheduler.proto` and a separate directory.** Both
// ends of this one are ours, but unlike `node.proto` this one has a Go consumer
// — the gateway — so it is on `services/Makefile`'s `PROTO_SRC` as well as on
// `build.rs`. The subdirectory is not decoration: `paths=source_relative` writes
// the generated Go next to the source, and Go allows one package per directory,
// so a second `option go_package` in `services/api/proto/` would not compile.
// # Metadata, in both directions
//
// Two things travel outside the messages, both copied from e2b's shape
// (`proxy_grpc.go` reads its tokens off gRPC metadata, not off proto fields):
//
// | key | direction | meaning |
// |---|---|---|
// | `x-agentenv-target-port` | request | the port the data-plane request was for; decides whether this is envd traffic |
// | `x-access-token` | request | the caller's envd access token; checked for `secure` sandboxes |
// | `x-agentenv-resume-refusal` | response trailer | why a `FAILED_PRECONDITION` refusal happened |
// | `x-agentenv-resume-origin-node` | response trailer | the node a pinned refusal named |
//
// 🔴 **The refusal reason is a trailer, not a status detail.** `Status::with_details`
// on the Rust side writes raw bytes into `grpc-status-details-bin`, and Go's
// `status.Details()` expects that trailer to hold a marshalled `google.rpc.Status`
// — so the two do not meet, and the reason would arrive as an undecodable blob
// on the only consumer that needs it. `node.proto` uses details because both of
// its ends are Rust.
//
// 🔴 **Two `FAILED_PRECONDITION` reasons, and they are not interchangeable.**
// A caller that cannot tell them apart backs off wrongly in one direction or the
// other:
//
// | reason | means | how long |
// |---|---|---|
// | `transition_in_progress` | somebody else is mid-operation on this sandbox | a moment; retry |
// | `auto_resume_disabled` | the sandbox's row forbids traffic-triggered wake-ups | until a user resumes it explicitly |
//
// 🔴 Neither means "try another node": a paused sandbox is a snapshot row any
// node can rebuild, and it is the api half that places the rebuild.
type SandboxResumeServiceClient interface {
	// Wakes a paused sandbox and says where it woke up.
	//
	// Idempotent in the way that matters: a sandbox that is already running is a
	// success carrying that sandbox's node and incarnation, not a conflict. The
	// gateway's caller is a user request that wants to reach the sandbox, and two
	// requests arriving together must both be able to.
	ResumeSandbox(ctx context.Context, in *SandboxResumeRequest, opts ...grpc.CallOption) (*SandboxResumeResponse, error)
}

type sandboxResumeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxResumeServiceClient(cc grpc.ClientConnInterface) SandboxResumeServiceClient {
	return &sandboxResumeServiceClient{cc}
}

func (c *sandboxResumeServiceClient) ResumeSandbox(ctx context.Context, in *SandboxResumeRequest, opts ...grpc.CallOption) (*SandboxResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxResumeResponse)
	err := c.cc.Invoke(ctx, SandboxResumeService_ResumeSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxResumeServiceServer is the server API for SandboxResumeService service.
// All implementations must embed UnimplementedSandboxResumeServiceServer
// for forward compatibility.
//
// The one thing the data plane asks the control plane for.
//
// 🔴 **One RPC, and it stays one RPC.** The gateway is a router: it resolves a
// sandbox to a node and forwards bytes. The only question it cannot answer from
// its own projection is "this sandbox is paused — wake it", and that is a
// decision, so it belongs to the API half. Everything else the gateway needs it
// already has. A second method here would be the beginning of the gateway
// asking the control plane to decide things on the request path, which is the
// arrangement this split exists to end.
//
// 🔴 **A separate file from `scheduler.proto` and a separate directory.** Both
// ends of this one are ours, but unlike `node.proto` this one has a Go consumer
// — the gateway — so it is on `services/Makefile`'s `PROTO_SRC` as well as on
// `build.rs`. The subdirectory is not decoration: `paths=source_relative` writes
// the generated Go next to the source, and Go allows one package per directory,
// so a second `option go_package` in `services/api/proto/` would not compile.
// # Metadata, in both directions
//
// Two things travel outside the messages, both copied from e2b's shape
// (`proxy_grpc.go` reads its tokens off gRPC metadata, not off proto fields):
//
// | key | direction | meaning |
// |---|---|---|
// | `x-agentenv-target-port` | request | the port the data-plane request was for; decides whether this is envd traffic |
// | `x-access-token` | request | the caller's envd access token; checked for `secure` sandboxes |
// | `x-agentenv-resume-refusal` | response trailer | why a `FAILED_PRECONDITION` refusal happened |
// | `x-agentenv-resume-origin-node` | response trailer | the node a pinned refusal named |
//
// 🔴 **The refusal reason is a trailer, not a status detail.** `Status::with_details`
// on the Rust side writes raw bytes into `grpc-status-details-bin`, and Go's
// `status.Details()` expects that trailer to hold a marshalled `google.rpc.Status`
// — so the two do not meet, and the reason would arrive as an undecodable blob
// on the only consumer that needs it. `node.proto` uses details because both of
// its ends are Rust.
//
// 🔴 **Two `FAILED_PRECONDITION` reasons, and they are not interchangeable.**
// A caller that cannot tell them apart backs off wrongly in one direction or the
// other:
//
// | reason | means | how long |
// |---|---|---|
// | `transition_in_progress` | somebody else is mid-operation on this sandbox | a moment; retry |
// | `auto_resume_disabled` | the sandbox's row forbids traffic-triggered wake-ups | until a user resumes it explicitly |
//
// 🔴 Neither means "try another node": a paused sandbox is a snapshot row any
// node can rebuild, and it is the api half that places the rebuild.
type SandboxResumeServiceServer interface {
	// Wakes a paused sandbox and says where it woke up.
	//
	// Idempotent in the way that matters: a sandbox that is already running is a
	// success carrying that sandbox's node and incarnation, not a conflict. The
	// gateway's caller is a user request that wants to reach the sandbox, and two
	// requests arriving together must both be able to.
	ResumeSandbox(context.Context, *SandboxResumeRequest) (*SandboxResumeResponse, error)
	mustEmbedUnimplementedSandboxResumeServiceServer()
}

// UnimplementedSandboxResumeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxResumeServiceServer struct{}

func (UnimplementedSandboxResumeServiceServer) ResumeSandbox(context.Context, *SandboxResumeRequest) (*SandboxResumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeSandbox not implemented")
}
func (UnimplementedSandboxResumeServiceServer) mustEmbedUnimplementedSandboxResumeServiceServer() {}
func (UnimplementedSandboxResumeServiceServer) testEmbeddedByValue()                              {}

// UnsafeSandboxResumeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxResumeServiceServer will
// result in compilation errors.
type UnsafeSandboxResumeServiceServer interface {
	mustEmbedUnimplementedSandboxResumeServiceServer()
}

func RegisterSandboxResumeServiceServer(s grpc.ServiceRegistrar, srv SandboxResumeServiceServer) {
	// If the following call panics, it indicates UnimplementedSandboxResumeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxResumeService_ServiceDesc, srv)
}

func _SandboxResumeService_ResumeSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxResumeServiceServer).ResumeSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxResumeService_ResumeSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxResumeServiceServer).ResumeSandbox(ctx, req.(*SandboxResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxResumeService_ServiceDesc is the grpc.ServiceDesc for SandboxResumeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxResumeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentenv.apiproxy.v1.SandboxResumeService",
	HandlerType: (*SandboxResumeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResumeSandbox",
			Handler:    _SandboxResumeService_ResumeSandbox_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/apiproxy/apiproxy.proto",
}
