// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/apiproxy/apiproxy.proto

package apiproxyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SandboxResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxResumeRequest) Reset() {
	*x = SandboxResumeRequest{}
	mi := &file_api_proto_apiproxy_apiproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxResumeRequest) ProtoMessage() {}

func (x *SandboxResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_apiproxy_apiproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxResumeRequest.ProtoReflect.Descriptor instead.
func (*SandboxResumeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_apiproxy_apiproxy_proto_rawDescGZIP(), []int{0}
}

func (x *SandboxResumeRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type SandboxResumeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node the sandbox is running on now.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Where to send the request that triggered this wake-up, so the gateway does
	// not have to look the node up a second time.
	//
	// 🔴 May be empty, and empty is not an error. A single-node deployment has no
	// placement source to name an address, and a caller that treated "" as an
	// address would proxy to nowhere. The gateway resolves the node itself when
	// this is empty — see `resume.Client` for the three-state read.
	NodeAddress string `protobuf:"bytes,2,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	// The incarnation this wake-up produced, for the gateway's execution fencing.
	//
	// 🔴 Present precisely because the alternative is a fencing gap: the request
	// that caused this resume is about to be forwarded, and without an
	// incarnation to expect, that first request is the one request in a sandbox's
	// life that travels unfenced.
	ExecutionId   string `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxResumeResponse) Reset() {
	*x = SandboxResumeResponse{}
	mi := &file_api_proto_apiproxy_apiproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxResumeResponse) ProtoMessage() {}

func (x *SandboxResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_apiproxy_apiproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxResumeResponse.ProtoReflect.Descriptor instead.
func (*SandboxResumeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_apiproxy_apiproxy_proto_rawDescGZIP(), []int{1}
}

func (x *SandboxResumeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SandboxResumeResponse) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

func (x *SandboxResumeResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

var File_api_proto_apiproxy_apiproxy_proto protoreflect.FileDescriptor

const file_api_proto_apiproxy_apiproxy_proto_rawDesc = "" +
	"\n" +
	"!api/proto/apiproxy/apiproxy.proto\x12\x14agentenv.apiproxy.v1\"5\n" +
	"\x14SandboxResumeRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"v\n" +
	"\x15SandboxResumeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\fnode_address\x18\x02 \x01(\tR\vnodeAddress\x12!\n" +
	"\fexecution_id\x18\x03 \x01(\tR\vexecutionId2\x80\x01\n" +
	"\x14SandboxResumeService\x12h\n" +
	"\rResumeSandbox\x12*.agentenv.apiproxy.v1.SandboxResumeRequest\x1a+.agentenv.apiproxy.v1.SandboxResumeResponseB1Z/agentenv/services/api/proto/apiproxy;apiproxyv1b\x06proto3"

var (
	file_api_proto_apiproxy_apiproxy_proto_rawDescOnce sync.Once
	file_api_proto_apiproxy_apiproxy_proto_rawDescData []byte
)

func file_api_proto_apiproxy_apiproxy_proto_rawDescGZIP() []byte {
	file_api_proto_apiproxy_apiproxy_proto_rawDescOnce.Do(func() {
		file_api_proto_apiproxy_apiproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_apiproxy_apiproxy_proto_rawDesc), len(file_api_proto_apiproxy_apiproxy_proto_rawDesc)))
	})
	return file_api_proto_apiproxy_apiproxy_proto_rawDescData
}

var file_api_proto_apiproxy_apiproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_apiproxy_apiproxy_proto_goTypes = []any{
	(*SandboxResumeRequest)(nil),  // 0: agentenv.apiproxy.v1.SandboxResumeRequest
	(*SandboxResumeResponse)(nil), // 1: agentenv.apiproxy.v1.SandboxResumeResponse
}
var file_api_proto_apiproxy_apiproxy_proto_depIdxs = []int32{
	0, // 0: agentenv.apiproxy.v1.SandboxResumeService.ResumeSandbox:input_type -> agentenv.apiproxy.v1.SandboxResumeRequest
	1, // 1: agentenv.apiproxy.v1.SandboxResumeService.ResumeSandbox:output_type -> agentenv.apiproxy.v1.SandboxResumeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_apiproxy_apiproxy_proto_init() }
func file_api_proto_apiproxy_apiproxy_proto_init() {
	if File_api_proto_apiproxy_apiproxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_apiproxy_apiproxy_proto_rawDesc), len(file_api_proto_apiproxy_apiproxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_apiproxy_apiproxy_proto_goTypes,
		DependencyIndexes: file_api_proto_apiproxy_apiproxy_proto_depIdxs,
		MessageInfos:      file_api_proto_apiproxy_apiproxy_proto_msgTypes,
	}.Build()
	File_api_proto_apiproxy_apiproxy_proto = out.File
	file_api_proto_apiproxy_apiproxy_proto_goTypes = nil
	file_api_proto_apiproxy_apiproxy_proto_depIdxs = nil
}
