// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/proto/scheduler.proto

package schedulerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Scheduler_Schedule_FullMethodName              = "/scheduler.v1.Scheduler/Schedule"
	Scheduler_ListNodes_FullMethodName             = "/scheduler.v1.Scheduler/ListNodes"
	Scheduler_LookupNode_FullMethodName            = "/scheduler.v1.Scheduler/LookupNode"
	Scheduler_RecordAssignment_FullMethodName      = "/scheduler.v1.Scheduler/RecordAssignment"
	Scheduler_Heartbeat_FullMethodName             = "/scheduler.v1.Scheduler/Heartbeat"
	Scheduler_ReportSandboxEvent_FullMethodName    = "/scheduler.v1.Scheduler/ReportSandboxEvent"
	Scheduler_ListObservedNodes_FullMethodName     = "/scheduler.v1.Scheduler/ListObservedNodes"
	Scheduler_ListP2PPeers_FullMethodName          = "/scheduler.v1.Scheduler/ListP2pPeers"
	Scheduler_RecordP2PArtifact_FullMethodName     = "/scheduler.v1.Scheduler/RecordP2pArtifact"
	Scheduler_ForgetP2PArtifact_FullMethodName     = "/scheduler.v1.Scheduler/ForgetP2pArtifact"
	Scheduler_LookupP2PArtifact_FullMethodName     = "/scheduler.v1.Scheduler/LookupP2pArtifact"
	Scheduler_GetNode_FullMethodName               = "/scheduler.v1.Scheduler/GetNode"
	Scheduler_UnregisterNode_FullMethodName        = "/scheduler.v1.Scheduler/UnregisterNode"
	Scheduler_ListRegistrySandboxes_FullMethodName = "/scheduler.v1.Scheduler/ListRegistrySandboxes"
)

// SchedulerClient is the client API for Scheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Scheduler is the placement and observation surface: gateways and nodes ask
// it where a sandbox is, tell it where one ended up, and report what they hold.
//
// 🔴 No method on this service may answer with codes.PermissionDenied. That
// code belongs to PausedRegistry, where it means "a superseded incarnation
// tried to write" (see ExecutionAuthority and TransitionSandboxRequest
// .execution_id). The gateway's scheduler error mapping has no branch for it
// and falls through to a 502, so returning it here turns a precise refusal
// into a misdiagnosed server fault.
type SchedulerClient interface {
	Schedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error)
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	LookupNode(ctx context.Context, in *LookupNodeRequest, opts ...grpc.CallOption) (*LookupNodeResponse, error)
	RecordAssignment(ctx context.Context, in *RecordAssignmentRequest, opts ...grpc.CallOption) (*RecordAssignmentResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	ReportSandboxEvent(ctx context.Context, in *ReportSandboxEventRequest, opts ...grpc.CallOption) (*ReportSandboxEventResponse, error)
	ListObservedNodes(ctx context.Context, in *ListObservedNodesRequest, opts ...grpc.CallOption) (*ListObservedNodesResponse, error)
	ListP2PPeers(ctx context.Context, in *ListP2PPeersRequest, opts ...grpc.CallOption) (*ListP2PPeersResponse, error)
	RecordP2PArtifact(ctx context.Context, in *RecordP2PArtifactRequest, opts ...grpc.CallOption) (*RecordP2PArtifactResponse, error)
	ForgetP2PArtifact(ctx context.Context, in *ForgetP2PArtifactRequest, opts ...grpc.CallOption) (*ForgetP2PArtifactResponse, error)
	LookupP2PArtifact(ctx context.Context, in *LookupP2PArtifactRequest, opts ...grpc.CallOption) (*LookupP2PArtifactResponse, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	UnregisterNode(ctx context.Context, in *UnregisterNodeRequest, opts ...grpc.CallOption) (*UnregisterNodeResponse, error)
	ListRegistrySandboxes(ctx context.Context, in *ListRegistrySandboxesRequest, opts ...grpc.CallOption) (*ListRegistrySandboxesResponse, error)
}

type schedulerClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerClient(cc grpc.ClientConnInterface) SchedulerClient {
	return &schedulerClient{cc}
}

func (c *schedulerClient) Schedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleResponse)
	err := c.cc.Invoke(ctx, Scheduler_Schedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, Scheduler_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) LookupNode(ctx context.Context, in *LookupNodeRequest, opts ...grpc.CallOption) (*LookupNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupNodeResponse)
	err := c.cc.Invoke(ctx, Scheduler_LookupNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) RecordAssignment(ctx context.Context, in *RecordAssignmentRequest, opts ...grpc.CallOption) (*RecordAssignmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordAssignmentResponse)
	err := c.cc.Invoke(ctx, Scheduler_RecordAssignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, Scheduler_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ReportSandboxEvent(ctx context.Context, in *ReportSandboxEventRequest, opts ...grpc.CallOption) (*ReportSandboxEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportSandboxEventResponse)
	err := c.cc.Invoke(ctx, Scheduler_ReportSandboxEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ListObservedNodes(ctx context.Context, in *ListObservedNodesRequest, opts ...grpc.CallOption) (*ListObservedNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListObservedNodesResponse)
	err := c.cc.Invoke(ctx, Scheduler_ListObservedNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ListP2PPeers(ctx context.Context, in *ListP2PPeersRequest, opts ...grpc.CallOption) (*ListP2PPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListP2PPeersResponse)
	err := c.cc.Invoke(ctx, Scheduler_ListP2PPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) RecordP2PArtifact(ctx context.Context, in *RecordP2PArtifactRequest, opts ...grpc.CallOption) (*RecordP2PArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordP2PArtifactResponse)
	err := c.cc.Invoke(ctx, Scheduler_RecordP2PArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ForgetP2PArtifact(ctx context.Context, in *ForgetP2PArtifactRequest, opts ...grpc.CallOption) (*ForgetP2PArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForgetP2PArtifactResponse)
	err := c.cc.Invoke(ctx, Scheduler_ForgetP2PArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) LookupP2PArtifact(ctx context.Context, in *LookupP2PArtifactRequest, opts ...grpc.CallOption) (*LookupP2PArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupP2PArtifactResponse)
	err := c.cc.Invoke(ctx, Scheduler_LookupP2PArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, Scheduler_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) UnregisterNode(ctx context.Context, in *UnregisterNodeRequest, opts ...grpc.CallOption) (*UnregisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterNodeResponse)
	err := c.cc.Invoke(ctx, Scheduler_UnregisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ListRegistrySandboxes(ctx context.Context, in *ListRegistrySandboxesRequest, opts ...grpc.CallOption) (*ListRegistrySandboxesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRegistrySandboxesResponse)
	err := c.cc.Invoke(ctx, Scheduler_ListRegistrySandboxes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerServer is the server API for Scheduler service.
// All implementations must embed UnimplementedSchedulerServer
// for forward compatibility.
//
// Scheduler is the placement and observation surface: gateways and nodes ask
// it where a sandbox is, tell it where one ended up, and report what they hold.
//
// 🔴 No method on this service may answer with codes.PermissionDenied. That
// code belongs to PausedRegistry, where it means "a superseded incarnation
// tried to write" (see ExecutionAuthority and TransitionSandboxRequest
// .execution_id). The gateway's scheduler error mapping has no branch for it
// and falls through to a 502, so returning it here turns a precise refusal
// into a misdiagnosed server fault.
type SchedulerServer interface {
	Schedule(context.Context, *ScheduleRequest) (*ScheduleResponse, error)
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	LookupNode(context.Context, *LookupNodeRequest) (*LookupNodeResponse, error)
	RecordAssignment(context.Context, *RecordAssignmentRequest) (*RecordAssignmentResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	ReportSandboxEvent(context.Context, *ReportSandboxEventRequest) (*ReportSandboxEventResponse, error)
	ListObservedNodes(context.Context, *ListObservedNodesRequest) (*ListObservedNodesResponse, error)
	ListP2PPeers(context.Context, *ListP2PPeersRequest) (*ListP2PPeersResponse, error)
	RecordP2PArtifact(context.Context, *RecordP2PArtifactRequest) (*RecordP2PArtifactResponse, error)
	ForgetP2PArtifact(context.Context, *ForgetP2PArtifactRequest) (*ForgetP2PArtifactResponse, error)
	LookupP2PArtifact(context.Context, *LookupP2PArtifactRequest) (*LookupP2PArtifactResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	UnregisterNode(context.Context, *UnregisterNodeRequest) (*UnregisterNodeResponse, error)
	ListRegistrySandboxes(context.Context, *ListRegistrySandboxesRequest) (*ListRegistrySandboxesResponse, error)
	mustEmbedUnimplementedSchedulerServer()
}

// UnimplementedSchedulerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulerServer struct{}

func (UnimplementedSchedulerServer) Schedule(context.Context, *ScheduleRequest) (*ScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Schedule not implemented")
}
func (UnimplementedSchedulerServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedSchedulerServer) LookupNode(context.Context, *LookupNodeRequest) (*LookupNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupNode not implemented")
}
func (UnimplementedSchedulerServer) RecordAssignment(context.Context, *RecordAssignmentRequest) (*RecordAssignmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordAssignment not implemented")
}
func (UnimplementedSchedulerServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedSchedulerServer) ReportSandboxEvent(context.Context, *ReportSandboxEventRequest) (*ReportSandboxEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportSandboxEvent not implemented")
}
func (UnimplementedSchedulerServer) ListObservedNodes(context.Context, *ListObservedNodesRequest) (*ListObservedNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListObservedNodes not implemented")
}
func (UnimplementedSchedulerServer) ListP2PPeers(context.Context, *ListP2PPeersRequest) (*ListP2PPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListP2PPeers not implemented")
}
func (UnimplementedSchedulerServer) RecordP2PArtifact(context.Context, *RecordP2PArtifactRequest) (*RecordP2PArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordP2PArtifact not implemented")
}
func (UnimplementedSchedulerServer) ForgetP2PArtifact(context.Context, *ForgetP2PArtifactRequest) (*ForgetP2PArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForgetP2PArtifact not implemented")
}
func (UnimplementedSchedulerServer) LookupP2PArtifact(context.Context, *LookupP2PArtifactRequest) (*LookupP2PArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupP2PArtifact not implemented")
}
func (UnimplementedSchedulerServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedSchedulerServer) UnregisterNode(context.Context, *UnregisterNodeRequest) (*UnregisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterNode not implemented")
}
func (UnimplementedSchedulerServer) ListRegistrySandboxes(context.Context, *ListRegistrySandboxesRequest) (*ListRegistrySandboxesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRegistrySandboxes not implemented")
}
func (UnimplementedSchedulerServer) mustEmbedUnimplementedSchedulerServer() {}
func (UnimplementedSchedulerServer) testEmbeddedByValue()                   {}

// UnsafeSchedulerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulerServer will
// result in compilation errors.
type UnsafeSchedulerServer interface {
	mustEmbedUnimplementedSchedulerServer()
}

func RegisterSchedulerServer(s grpc.ServiceRegistrar, srv SchedulerServer) {
	// If the following call panics, it indicates UnimplementedSchedulerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Scheduler_ServiceDesc, srv)
}

func _Scheduler_Schedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).Schedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_Schedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).Schedule(ctx, req.(*ScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_LookupNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).LookupNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_LookupNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).LookupNode(ctx, req.(*LookupNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_RecordAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).RecordAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_RecordAssignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).RecordAssignment(ctx, req.(*RecordAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ReportSandboxEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportSandboxEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ReportSandboxEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_ReportSandboxEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ReportSandboxEvent(ctx, req.(*ReportSandboxEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ListObservedNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObservedNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ListObservedNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_ListObservedNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ListObservedNodes(ctx, req.(*ListObservedNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ListP2PPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListP2PPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ListP2PPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_ListP2PPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ListP2PPeers(ctx, req.(*ListP2PPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_RecordP2PArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordP2PArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).RecordP2PArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_RecordP2PArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).RecordP2PArtifact(ctx, req.(*RecordP2PArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ForgetP2PArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetP2PArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ForgetP2PArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_ForgetP2PArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ForgetP2PArtifact(ctx, req.(*ForgetP2PArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_LookupP2PArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupP2PArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).LookupP2PArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_LookupP2PArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).LookupP2PArtifact(ctx, req.(*LookupP2PArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_UnregisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).UnregisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_UnregisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).UnregisterNode(ctx, req.(*UnregisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ListRegistrySandboxes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRegistrySandboxesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ListRegistrySandboxes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_ListRegistrySandboxes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ListRegistrySandboxes(ctx, req.(*ListRegistrySandboxesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Scheduler_ServiceDesc is the grpc.ServiceDesc for Scheduler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scheduler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.v1.Scheduler",
	HandlerType: (*SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Schedule",
			Handler:    _Scheduler_Schedule_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _Scheduler_ListNodes_Handler,
		},
		{
			MethodName: "LookupNode",
			Handler:    _Scheduler_LookupNode_Handler,
		},
		{
			MethodName: "RecordAssignment",
			Handler:    _Scheduler_RecordAssignment_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Scheduler_Heartbeat_Handler,
		},
		{
			MethodName: "ReportSandboxEvent",
			Handler:    _Scheduler_ReportSandboxEvent_Handler,
		},
		{
			MethodName: "ListObservedNodes",
			Handler:    _Scheduler_ListObservedNodes_Handler,
		},
		{
			MethodName: "ListP2pPeers",
			Handler:    _Scheduler_ListP2PPeers_Handler,
		},
		{
			MethodName: "RecordP2pArtifact",
			Handler:    _Scheduler_RecordP2PArtifact_Handler,
		},
		{
			MethodName: "ForgetP2pArtifact",
			Handler:    _Scheduler_ForgetP2PArtifact_Handler,
		},
		{
			MethodName: "LookupP2pArtifact",
			Handler:    _Scheduler_LookupP2PArtifact_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _Scheduler_GetNode_Handler,
		},
		{
			MethodName: "UnregisterNode",
			Handler:    _Scheduler_UnregisterNode_Handler,
		},
		{
			MethodName: "ListRegistrySandboxes",
			Handler:    _Scheduler_ListRegistrySandboxes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/scheduler.proto",
}

const (
	PausedRegistry_GetSandboxes_FullMethodName        = "/scheduler.v1.PausedRegistry/GetSandboxes"
	PausedRegistry_TransitionSandbox_FullMethodName   = "/scheduler.v1.PausedRegistry/TransitionSandbox"
	PausedRegistry_AcquireSandbox_FullMethodName      = "/scheduler.v1.PausedRegistry/AcquireSandbox"
	PausedRegistry_RenewNodeLease_FullMethodName      = "/scheduler.v1.PausedRegistry/RenewNodeLease"
	PausedRegistry_ReleaseNodeHoldings_FullMethodName = "/scheduler.v1.PausedRegistry/ReleaseNodeHoldings"
)

// PausedRegistryClient is the client API for PausedRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ─────────────────────────────────────────────────────────────────────────────
// PausedRegistry: the paused-sandbox registry, served by whoever owns the
// database instead of by every node against it directly.
//
// The five methods here cover thirteen operations on the node side. The
// narrowing is deliberate: a wire contract shaped like the node's own trait
// would make "the node decides" a cross-process contract, and the next stage
// begins by deleting that. What survives the next stage is shaped like this.
//
// Every request carries cluster_id and node_id. The node scopes each statement
// rather than the connection, and one cluster reaching another's sandboxes is a
// case its tests cover; making the scope implicit here is how that property
// gets lost.
//
// 🔴 No method may answer a failure with an empty result. A sandbox missing
// from GetSandboxes means the row does not exist, and the caller deletes local
// artifacts on the strength of that. Anything that went wrong is an RPC error.
//
// 🔴 Two refusals on this service look alike and are not interchangeable. A
// write from a superseded incarnation is codes.PermissionDenied, and it is
// terminal: the caller must not retry it, must not publish behind it, and must
// not delete the snapshot it was about to replace. A write whose generation
// moved is codes.Aborted, and the caller re-reads the row and tries again.
//
// Wherever the first one has to be named as a string — a header value, a JSON
// body, a log field — the name is `sandbox_execution_superseded`.
//
// 🔴 PermissionDenied belongs to this service alone; see the note on the
// Scheduler service for why it may never appear there.
// ─────────────────────────────────────────────────────────────────────────────
type PausedRegistryClient interface {
	// Reads rows in bulk. All-or-nothing: any backend failure is an error, never
	// a shorter map. Carries no metadata — no bulk consumer reads it.
	GetSandboxes(ctx context.Context, in *GetSandboxesRequest, opts ...grpc.CallOption) (*GetSandboxesResponse, error)
	// Moves a sandbox between states. Covers begin_pause, complete_pause,
	// mark_local_only, mark_running, release_claim and remove.
	TransitionSandbox(ctx context.Context, in *TransitionSandboxRequest, opts ...grpc.CallOption) (*TransitionSandboxResponse, error)
	// Takes a sandbox for a resume, deciding on the server which of the three
	// cases applies. Carries metadata, for the one row it answers with.
	AcquireSandbox(ctx context.Context, in *AcquireSandboxRequest, opts ...grpc.CallOption) (*AcquireSandboxResponse, error)
	// Extends the lease on everything a node reports holding.
	RenewNodeLease(ctx context.Context, in *RenewNodeLeaseRequest, opts ...grpc.CallOption) (*RenewNodeLeaseResponse, error)
	// Frees what a previous process on the same machine was holding.
	ReleaseNodeHoldings(ctx context.Context, in *ReleaseNodeHoldingsRequest, opts ...grpc.CallOption) (*ReleaseNodeHoldingsResponse, error)
}

type pausedRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewPausedRegistryClient(cc grpc.ClientConnInterface) PausedRegistryClient {
	return &pausedRegistryClient{cc}
}

func (c *pausedRegistryClient) GetSandboxes(ctx context.Context, in *GetSandboxesRequest, opts ...grpc.CallOption) (*GetSandboxesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSandboxesResponse)
	err := c.cc.Invoke(ctx, PausedRegistry_GetSandboxes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pausedRegistryClient) TransitionSandbox(ctx context.Context, in *TransitionSandboxRequest, opts ...grpc.CallOption) (*TransitionSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransitionSandboxResponse)
	err := c.cc.Invoke(ctx, PausedRegistry_TransitionSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pausedRegistryClient) AcquireSandbox(ctx context.Context, in *AcquireSandboxRequest, opts ...grpc.CallOption) (*AcquireSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireSandboxResponse)
	err := c.cc.Invoke(ctx, PausedRegistry_AcquireSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pausedRegistryClient) RenewNodeLease(ctx context.Context, in *RenewNodeLeaseRequest, opts ...grpc.CallOption) (*RenewNodeLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewNodeLeaseResponse)
	err := c.cc.Invoke(ctx, PausedRegistry_RenewNodeLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pausedRegistryClient) ReleaseNodeHoldings(ctx context.Context, in *ReleaseNodeHoldingsRequest, opts ...grpc.CallOption) (*ReleaseNodeHoldingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseNodeHoldingsResponse)
	err := c.cc.Invoke(ctx, PausedRegistry_ReleaseNodeHoldings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PausedRegistryServer is the server API for PausedRegistry service.
// All implementations must embed UnimplementedPausedRegistryServer
// for forward compatibility.
//
// ─────────────────────────────────────────────────────────────────────────────
// PausedRegistry: the paused-sandbox registry, served by whoever owns the
// database instead of by every node against it directly.
//
// The five methods here cover thirteen operations on the node side. The
// narrowing is deliberate: a wire contract shaped like the node's own trait
// would make "the node decides" a cross-process contract, and the next stage
// begins by deleting that. What survives the next stage is shaped like this.
//
// Every request carries cluster_id and node_id. The node scopes each statement
// rather than the connection, and one cluster reaching another's sandboxes is a
// case its tests cover; making the scope implicit here is how that property
// gets lost.
//
// 🔴 No method may answer a failure with an empty result. A sandbox missing
// from GetSandboxes means the row does not exist, and the caller deletes local
// artifacts on the strength of that. Anything that went wrong is an RPC error.
//
// 🔴 Two refusals on this service look alike and are not interchangeable. A
// write from a superseded incarnation is codes.PermissionDenied, and it is
// terminal: the caller must not retry it, must not publish behind it, and must
// not delete the snapshot it was about to replace. A write whose generation
// moved is codes.Aborted, and the caller re-reads the row and tries again.
//
// Wherever the first one has to be named as a string — a header value, a JSON
// body, a log field — the name is `sandbox_execution_superseded`.
//
// 🔴 PermissionDenied belongs to this service alone; see the note on the
// Scheduler service for why it may never appear there.
// ─────────────────────────────────────────────────────────────────────────────
type PausedRegistryServer interface {
	// Reads rows in bulk. All-or-nothing: any backend failure is an error, never
	// a shorter map. Carries no metadata — no bulk consumer reads it.
	GetSandboxes(context.Context, *GetSandboxesRequest) (*GetSandboxesResponse, error)
	// Moves a sandbox between states. Covers begin_pause, complete_pause,
	// mark_local_only, mark_running, release_claim and remove.
	TransitionSandbox(context.Context, *TransitionSandboxRequest) (*TransitionSandboxResponse, error)
	// Takes a sandbox for a resume, deciding on the server which of the three
	// cases applies. Carries metadata, for the one row it answers with.
	AcquireSandbox(context.Context, *AcquireSandboxRequest) (*AcquireSandboxResponse, error)
	// Extends the lease on everything a node reports holding.
	RenewNodeLease(context.Context, *RenewNodeLeaseRequest) (*RenewNodeLeaseResponse, error)
	// Frees what a previous process on the same machine was holding.
	ReleaseNodeHoldings(context.Context, *ReleaseNodeHoldingsRequest) (*ReleaseNodeHoldingsResponse, error)
	mustEmbedUnimplementedPausedRegistryServer()
}

// UnimplementedPausedRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPausedRegistryServer struct{}

func (UnimplementedPausedRegistryServer) GetSandboxes(context.Context, *GetSandboxesRequest) (*GetSandboxesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSandboxes not implemented")
}
func (UnimplementedPausedRegistryServer) TransitionSandbox(context.Context, *TransitionSandboxRequest) (*TransitionSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransitionSandbox not implemented")
}
func (UnimplementedPausedRegistryServer) AcquireSandbox(context.Context, *AcquireSandboxRequest) (*AcquireSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcquireSandbox not implemented")
}
func (UnimplementedPausedRegistryServer) RenewNodeLease(context.Context, *RenewNodeLeaseRequest) (*RenewNodeLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewNodeLease not implemented")
}
func (UnimplementedPausedRegistryServer) ReleaseNodeHoldings(context.Context, *ReleaseNodeHoldingsRequest) (*ReleaseNodeHoldingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseNodeHoldings not implemented")
}
func (UnimplementedPausedRegistryServer) mustEmbedUnimplementedPausedRegistryServer() {}
func (UnimplementedPausedRegistryServer) testEmbeddedByValue()                        {}

// UnsafePausedRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PausedRegistryServer will
// result in compilation errors.
type UnsafePausedRegistryServer interface {
	mustEmbedUnimplementedPausedRegistryServer()
}

func RegisterPausedRegistryServer(s grpc.ServiceRegistrar, srv PausedRegistryServer) {
	// If the following call panics, it indicates UnimplementedPausedRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PausedRegistry_ServiceDesc, srv)
}

func _PausedRegistry_GetSandboxes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PausedRegistryServer).GetSandboxes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PausedRegistry_GetSandboxes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PausedRegistryServer).GetSandboxes(ctx, req.(*GetSandboxesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PausedRegistry_TransitionSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PausedRegistryServer).TransitionSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PausedRegistry_TransitionSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PausedRegistryServer).TransitionSandbox(ctx, req.(*TransitionSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PausedRegistry_AcquireSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PausedRegistryServer).AcquireSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PausedRegistry_AcquireSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PausedRegistryServer).AcquireSandbox(ctx, req.(*AcquireSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PausedRegistry_RenewNodeLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewNodeLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PausedRegistryServer).RenewNodeLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PausedRegistry_RenewNodeLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PausedRegistryServer).RenewNodeLease(ctx, req.(*RenewNodeLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PausedRegistry_ReleaseNodeHoldings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseNodeHoldingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PausedRegistryServer).ReleaseNodeHoldings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PausedRegistry_ReleaseNodeHoldings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PausedRegistryServer).ReleaseNodeHoldings(ctx, req.(*ReleaseNodeHoldingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PausedRegistry_ServiceDesc is the grpc.ServiceDesc for PausedRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PausedRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.v1.PausedRegistry",
	HandlerType: (*PausedRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSandboxes",
			Handler:    _PausedRegistry_GetSandboxes_Handler,
		},
		{
			MethodName: "TransitionSandbox",
			Handler:    _PausedRegistry_TransitionSandbox_Handler,
		},
		{
			MethodName: "AcquireSandbox",
			Handler:    _PausedRegistry_AcquireSandbox_Handler,
		},
		{
			MethodName: "RenewNodeLease",
			Handler:    _PausedRegistry_RenewNodeLease_Handler,
		},
		{
			MethodName: "ReleaseNodeHoldings",
			Handler:    _PausedRegistry_ReleaseNodeHoldings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/scheduler.proto",
}

const (
	SnapshotCatalog_BeginSnapshot_FullMethodName   = "/scheduler.v1.SnapshotCatalog/BeginSnapshot"
	SnapshotCatalog_CommitSnapshot_FullMethodName  = "/scheduler.v1.SnapshotCatalog/CommitSnapshot"
	SnapshotCatalog_FailSnapshot_FullMethodName    = "/scheduler.v1.SnapshotCatalog/FailSnapshot"
	SnapshotCatalog_GetSnapshot_FullMethodName     = "/scheduler.v1.SnapshotCatalog/GetSnapshot"
	SnapshotCatalog_ListSnapshots_FullMethodName   = "/scheduler.v1.SnapshotCatalog/ListSnapshots"
	SnapshotCatalog_DeleteSnapshot_FullMethodName  = "/scheduler.v1.SnapshotCatalog/DeleteSnapshot"
	SnapshotCatalog_ResolveAlias_FullMethodName    = "/scheduler.v1.SnapshotCatalog/ResolveAlias"
	SnapshotCatalog_StartBuild_FullMethodName      = "/scheduler.v1.SnapshotCatalog/StartBuild"
	SnapshotCatalog_RenewBuildLease_FullMethodName = "/scheduler.v1.SnapshotCatalog/RenewBuildLease"
	SnapshotCatalog_GetBuild_FullMethodName        = "/scheduler.v1.SnapshotCatalog/GetBuild"
)

// SnapshotCatalogClient is the client API for SnapshotCatalog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ─────────────────────────────────────────────────────────────────────────────
// SnapshotCatalog: the snapshot and template catalog, served by whoever owns
// the database instead of by every node against it directly.
//
// Same shape and the same reason as PausedRegistry above. The reason worth
// restating is the one that decided it: only a catalog that lives beside
// `paused_sandboxes` can put a pause's registry transition and the catalog's
// own row in *one* statement. A node holding its own connection would have two,
// on two sockets, and "paused but absent from the catalog" would stay a window
// that exists. Every write RPC below therefore carries an optional
// CatalogPausedTransition, and that field is the whole point of the service.
//
// 🔴 The payload is opaque here and must stay opaque. `committed_payload` is a
// CommittedSnapshot as the node serialised it; `build_error_json` is a
// TemplateBuildErrorReason, which has a hand-written Deserialize with a legacy
// string form. Neither has a Go type, neither may grow one. What this service
// is allowed to know is the scalar columns — enough to index, filter, order and
// fence, and nothing else. A Go struct mirroring CommittedSnapshot is the
// failure this note exists to prevent: it makes the node's domain model a
// cross-process contract, and the phase after this one begins by deleting the
// process on the other end.
//
// 🔴 Milliseconds, not the microseconds PausedRegistry uses. The two services
// disagree on purpose: `paused_sandboxes` stores timestamptz, whose resolution
// is a microsecond, while the catalog's time columns are BIGINT milliseconds
// because SnapshotRecord.created_at_unix_ms is an i64 of milliseconds and the
// public pagination cursor is rendered from it. Passing microseconds here would
// round-trip a cursor through a unit it does not have and land the boundary on
// the wrong row. The one exception is inside CatalogPausedTransition, which
// speaks to the other table and keeps that table's unit.
//
// 🔴 A refusal this service expects is an outcome, not a status code. A commit
// that lost its fence, an alias somebody else holds, a template already
// building — the caller branches on all three, and a gRPC code cannot carry
// which row won or what the status is now. Status codes stay for the failures
// nobody can act on: UNAVAILABLE until the migration has run, and the usual
// transport faults. No method may report a failure as an empty success.
// ─────────────────────────────────────────────────────────────────────────────
type SnapshotCatalogClient interface {
	// Creates the catalog row before any bytes exist: a template at `waiting`, or
	// the `building` row a pause opens. Carries begin_pause when it is a pause.
	BeginSnapshot(ctx context.Context, in *BeginSnapshotRequest, opts ...grpc.CallOption) (*BeginSnapshotResponse, error)
	// Flips a row to `ready` — the only writer that does. Fenced on the row still
	// being `building`. Carries complete_pause, or mark_local_only when the bytes
	// reached the node but not the shared repository.
	CommitSnapshot(ctx context.Context, in *CommitSnapshotRequest, opts ...grpc.CallOption) (*CommitSnapshotResponse, error)
	// Moves a row to `error` with a reason. Covers a failed template build and a
	// pause whose publish produced no payload at all.
	FailSnapshot(ctx context.Context, in *FailSnapshotRequest, opts ...grpc.CallOption) (*FailSnapshotResponse, error)
	// Reads one row by id or alias.
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error)
	// Reads one keyset page.
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
	// Soft-deletes one row and drops the alias that pointed at it.
	DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error)
	// Resolves an alias to the snapshot id it currently names.
	ResolveAlias(ctx context.Context, in *ResolveAliasRequest, opts ...grpc.CallOption) (*ResolveAliasResponse, error)
	// Admits one build: the cluster-wide cap, the per-template exclusion and the
	// waiting -> building transition, in one transaction.
	StartBuild(ctx context.Context, in *StartBuildRequest, opts ...grpc.CallOption) (*StartBuildResponse, error)
	// Says the builder is still alive. A build that stops saying so is reaped,
	// and the answer tells the builder it was.
	RenewBuildLease(ctx context.Context, in *RenewBuildLeaseRequest, opts ...grpc.CallOption) (*RenewBuildLeaseResponse, error)
	// Reads one build row, deliberately without the `ready` predicate every
	// resolving query carries: this endpoint exists to look at builds that are
	// still running or have failed.
	GetBuild(ctx context.Context, in *GetBuildRequest, opts ...grpc.CallOption) (*GetBuildResponse, error)
}

type snapshotCatalogClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapshotCatalogClient(cc grpc.ClientConnInterface) SnapshotCatalogClient {
	return &snapshotCatalogClient{cc}
}

func (c *snapshotCatalogClient) BeginSnapshot(ctx context.Context, in *BeginSnapshotRequest, opts ...grpc.CallOption) (*BeginSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginSnapshotResponse)
	err := c.cc.Invoke(ctx, SnapshotCatalog_BeginSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotCatalogClient) CommitSnapshot(ctx context.Context, in *CommitSnapshotRequest, opts ...grpc.CallOption) (*CommitSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitSnapshotResponse)
	err := c.cc.Invoke(ctx, SnapshotCatalog_CommitSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotCatalogClient) FailSnapshot(ctx context.Context, in *FailSnapshotRequest, opts ...grpc.CallOption) (*FailSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FailSnapshotResponse)
	err := c.cc.Invoke(ctx, SnapshotCatalog_FailSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotCatalogClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnapshotResponse)
	err := c.cc.Invoke(ctx, SnapshotCatalog_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotCatalogClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, SnapshotCatalog_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotCatalogClient) DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSnapshotResponse)
	err := c.cc.Invoke(ctx, SnapshotCatalog_DeleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotCatalogClient) ResolveAlias(ctx context.Context, in *ResolveAliasRequest, opts ...grpc.CallOption) (*ResolveAliasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveAliasResponse)
	err := c.cc.Invoke(ctx, SnapshotCatalog_ResolveAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotCatalogClient) StartBuild(ctx context.Context, in *StartBuildRequest, opts ...grpc.CallOption) (*StartBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartBuildResponse)
	err := c.cc.Invoke(ctx, SnapshotCatalog_StartBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotCatalogClient) RenewBuildLease(ctx context.Context, in *RenewBuildLeaseRequest, opts ...grpc.CallOption) (*RenewBuildLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewBuildLeaseResponse)
	err := c.cc.Invoke(ctx, SnapshotCatalog_RenewBuildLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotCatalogClient) GetBuild(ctx context.Context, in *GetBuildRequest, opts ...grpc.CallOption) (*GetBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBuildResponse)
	err := c.cc.Invoke(ctx, SnapshotCatalog_GetBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapshotCatalogServer is the server API for SnapshotCatalog service.
// All implementations must embed UnimplementedSnapshotCatalogServer
// for forward compatibility.
//
// ─────────────────────────────────────────────────────────────────────────────
// SnapshotCatalog: the snapshot and template catalog, served by whoever owns
// the database instead of by every node against it directly.
//
// Same shape and the same reason as PausedRegistry above. The reason worth
// restating is the one that decided it: only a catalog that lives beside
// `paused_sandboxes` can put a pause's registry transition and the catalog's
// own row in *one* statement. A node holding its own connection would have two,
// on two sockets, and "paused but absent from the catalog" would stay a window
// that exists. Every write RPC below therefore carries an optional
// CatalogPausedTransition, and that field is the whole point of the service.
//
// 🔴 The payload is opaque here and must stay opaque. `committed_payload` is a
// CommittedSnapshot as the node serialised it; `build_error_json` is a
// TemplateBuildErrorReason, which has a hand-written Deserialize with a legacy
// string form. Neither has a Go type, neither may grow one. What this service
// is allowed to know is the scalar columns — enough to index, filter, order and
// fence, and nothing else. A Go struct mirroring CommittedSnapshot is the
// failure this note exists to prevent: it makes the node's domain model a
// cross-process contract, and the phase after this one begins by deleting the
// process on the other end.
//
// 🔴 Milliseconds, not the microseconds PausedRegistry uses. The two services
// disagree on purpose: `paused_sandboxes` stores timestamptz, whose resolution
// is a microsecond, while the catalog's time columns are BIGINT milliseconds
// because SnapshotRecord.created_at_unix_ms is an i64 of milliseconds and the
// public pagination cursor is rendered from it. Passing microseconds here would
// round-trip a cursor through a unit it does not have and land the boundary on
// the wrong row. The one exception is inside CatalogPausedTransition, which
// speaks to the other table and keeps that table's unit.
//
// 🔴 A refusal this service expects is an outcome, not a status code. A commit
// that lost its fence, an alias somebody else holds, a template already
// building — the caller branches on all three, and a gRPC code cannot carry
// which row won or what the status is now. Status codes stay for the failures
// nobody can act on: UNAVAILABLE until the migration has run, and the usual
// transport faults. No method may report a failure as an empty success.
// ─────────────────────────────────────────────────────────────────────────────
type SnapshotCatalogServer interface {
	// Creates the catalog row before any bytes exist: a template at `waiting`, or
	// the `building` row a pause opens. Carries begin_pause when it is a pause.
	BeginSnapshot(context.Context, *BeginSnapshotRequest) (*BeginSnapshotResponse, error)
	// Flips a row to `ready` — the only writer that does. Fenced on the row still
	// being `building`. Carries complete_pause, or mark_local_only when the bytes
	// reached the node but not the shared repository.
	CommitSnapshot(context.Context, *CommitSnapshotRequest) (*CommitSnapshotResponse, error)
	// Moves a row to `error` with a reason. Covers a failed template build and a
	// pause whose publish produced no payload at all.
	FailSnapshot(context.Context, *FailSnapshotRequest) (*FailSnapshotResponse, error)
	// Reads one row by id or alias.
	GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error)
	// Reads one keyset page.
	ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	// Soft-deletes one row and drops the alias that pointed at it.
	DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error)
	// Resolves an alias to the snapshot id it currently names.
	ResolveAlias(context.Context, *ResolveAliasRequest) (*ResolveAliasResponse, error)
	// Admits one build: the cluster-wide cap, the per-template exclusion and the
	// waiting -> building transition, in one transaction.
	StartBuild(context.Context, *StartBuildRequest) (*StartBuildResponse, error)
	// Says the builder is still alive. A build that stops saying so is reaped,
	// and the answer tells the builder it was.
	RenewBuildLease(context.Context, *RenewBuildLeaseRequest) (*RenewBuildLeaseResponse, error)
	// Reads one build row, deliberately without the `ready` predicate every
	// resolving query carries: this endpoint exists to look at builds that are
	// still running or have failed.
	GetBuild(context.Context, *GetBuildRequest) (*GetBuildResponse, error)
	mustEmbedUnimplementedSnapshotCatalogServer()
}

// UnimplementedSnapshotCatalogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnapshotCatalogServer struct{}

func (UnimplementedSnapshotCatalogServer) BeginSnapshot(context.Context, *BeginSnapshotRequest) (*BeginSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginSnapshot not implemented")
}
func (UnimplementedSnapshotCatalogServer) CommitSnapshot(context.Context, *CommitSnapshotRequest) (*CommitSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitSnapshot not implemented")
}
func (UnimplementedSnapshotCatalogServer) FailSnapshot(context.Context, *FailSnapshotRequest) (*FailSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FailSnapshot not implemented")
}
func (UnimplementedSnapshotCatalogServer) GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedSnapshotCatalogServer) ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedSnapshotCatalogServer) DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedSnapshotCatalogServer) ResolveAlias(context.Context, *ResolveAliasRequest) (*ResolveAliasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveAlias not implemented")
}
func (UnimplementedSnapshotCatalogServer) StartBuild(context.Context, *StartBuildRequest) (*StartBuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartBuild not implemented")
}
func (UnimplementedSnapshotCatalogServer) RenewBuildLease(context.Context, *RenewBuildLeaseRequest) (*RenewBuildLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewBuildLease not implemented")
}
func (UnimplementedSnapshotCatalogServer) GetBuild(context.Context, *GetBuildRequest) (*GetBuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBuild not implemented")
}
func (UnimplementedSnapshotCatalogServer) mustEmbedUnimplementedSnapshotCatalogServer() {}
func (UnimplementedSnapshotCatalogServer) testEmbeddedByValue()                         {}

// UnsafeSnapshotCatalogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnapshotCatalogServer will
// result in compilation errors.
type UnsafeSnapshotCatalogServer interface {
	mustEmbedUnimplementedSnapshotCatalogServer()
}

func RegisterSnapshotCatalogServer(s grpc.ServiceRegistrar, srv SnapshotCatalogServer) {
	// If the following call panics, it indicates UnimplementedSnapshotCatalogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnapshotCatalog_ServiceDesc, srv)
}

func _SnapshotCatalog_BeginSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotCatalogServer).BeginSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotCatalog_BeginSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotCatalogServer).BeginSnapshot(ctx, req.(*BeginSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotCatalog_CommitSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotCatalogServer).CommitSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotCatalog_CommitSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotCatalogServer).CommitSnapshot(ctx, req.(*CommitSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotCatalog_FailSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotCatalogServer).FailSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotCatalog_FailSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotCatalogServer).FailSnapshot(ctx, req.(*FailSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotCatalog_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotCatalogServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotCatalog_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotCatalogServer).GetSnapshot(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotCatalog_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotCatalogServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotCatalog_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotCatalogServer).ListSnapshots(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotCatalog_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotCatalogServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotCatalog_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotCatalogServer).DeleteSnapshot(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotCatalog_ResolveAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotCatalogServer).ResolveAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotCatalog_ResolveAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotCatalogServer).ResolveAlias(ctx, req.(*ResolveAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotCatalog_StartBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotCatalogServer).StartBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotCatalog_StartBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotCatalogServer).StartBuild(ctx, req.(*StartBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotCatalog_RenewBuildLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewBuildLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotCatalogServer).RenewBuildLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotCatalog_RenewBuildLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotCatalogServer).RenewBuildLease(ctx, req.(*RenewBuildLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotCatalog_GetBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotCatalogServer).GetBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotCatalog_GetBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotCatalogServer).GetBuild(ctx, req.(*GetBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnapshotCatalog_ServiceDesc is the grpc.ServiceDesc for SnapshotCatalog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnapshotCatalog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.v1.SnapshotCatalog",
	HandlerType: (*SnapshotCatalogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeginSnapshot",
			Handler:    _SnapshotCatalog_BeginSnapshot_Handler,
		},
		{
			MethodName: "CommitSnapshot",
			Handler:    _SnapshotCatalog_CommitSnapshot_Handler,
		},
		{
			MethodName: "FailSnapshot",
			Handler:    _SnapshotCatalog_FailSnapshot_Handler,
		},
		{
			MethodName: "GetSnapshot",
			Handler:    _SnapshotCatalog_GetSnapshot_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _SnapshotCatalog_ListSnapshots_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _SnapshotCatalog_DeleteSnapshot_Handler,
		},
		{
			MethodName: "ResolveAlias",
			Handler:    _SnapshotCatalog_ResolveAlias_Handler,
		},
		{
			MethodName: "StartBuild",
			Handler:    _SnapshotCatalog_StartBuild_Handler,
		},
		{
			MethodName: "RenewBuildLease",
			Handler:    _SnapshotCatalog_RenewBuildLease_Handler,
		},
		{
			MethodName: "GetBuild",
			Handler:    _SnapshotCatalog_GetBuild_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/scheduler.proto",
}
