// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/scheduler.proto

package schedulerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeStatus describes the effective state of a node as derived by the
// scheduler from its discovery state and heartbeat history.
//
//	active  + heartbeat OK      → READY        — accepts new sandboxes
//	active  + no heartbeat      → CONNECTING    — discovered but not yet confirmed
//	active  + heartbeat timeout → UNHEALTHY     — heartbeat lost
//	lingering + heartbeat OK    → LINGERING     — terminating, draining existing work
//	lingering + no heartbeat    → CONNECTING    — terminating, never confirmed
//	lingering + heartbeat timeout → UNHEALTHY   — terminating, heartbeat lost
//
// DRAINING is different in kind from the rows above: it is not derived, it is
// what the node itself reports after being isolated through its own admin API.
// A node reports it while it is still perfectly healthy, so it never overrides
// a derived status — LINGERING and UNHEALTHY both win over it, because a pod
// that is going away, or a node that stopped answering, is the stronger fact.
type NodeStatus int32

const (
	NodeStatus_NODE_STATUS_UNSPECIFIED NodeStatus = 0
	NodeStatus_NODE_STATUS_READY       NodeStatus = 1
	NodeStatus_NODE_STATUS_CONNECTING  NodeStatus = 2
	NodeStatus_NODE_STATUS_UNHEALTHY   NodeStatus = 3
	NodeStatus_NODE_STATUS_LINGERING   NodeStatus = 4
	// Node-reported isolation: serving existing sandboxes, refusing new work.
	NodeStatus_NODE_STATUS_DRAINING NodeStatus = 5
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNSPECIFIED",
		1: "NODE_STATUS_READY",
		2: "NODE_STATUS_CONNECTING",
		3: "NODE_STATUS_UNHEALTHY",
		4: "NODE_STATUS_LINGERING",
		5: "NODE_STATUS_DRAINING",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNSPECIFIED": 0,
		"NODE_STATUS_READY":       1,
		"NODE_STATUS_CONNECTING":  2,
		"NODE_STATUS_UNHEALTHY":   3,
		"NODE_STATUS_LINGERING":   4,
		"NODE_STATUS_DRAINING":    5,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_scheduler_proto_enumTypes[0].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_api_proto_scheduler_proto_enumTypes[0]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{0}
}

// How a node reaches the egress broker, as the node itself reports it.
//
// 3 and 4 named the cluster-wide broker Deployment a node reached over TLS.
// No build emits them; an api half that receives one decodes it as
// UNSPECIFIED, which is not a placement target — which is the direction a
// half-rolled fleet has to fail in.
type EgressBrokerState int32

const (
	EgressBrokerState_EGRESS_BROKER_STATE_UNSPECIFIED       EgressBrokerState = 0
	EgressBrokerState_EGRESS_BROKER_STATE_DISABLED          EgressBrokerState = 1
	EgressBrokerState_EGRESS_BROKER_STATE_EMBEDDED          EgressBrokerState = 2
	EgressBrokerState_EGRESS_BROKER_STATE_LOCAL_OK          EgressBrokerState = 5
	EgressBrokerState_EGRESS_BROKER_STATE_LOCAL_UNREACHABLE EgressBrokerState = 6
)

// Enum value maps for EgressBrokerState.
var (
	EgressBrokerState_name = map[int32]string{
		0: "EGRESS_BROKER_STATE_UNSPECIFIED",
		1: "EGRESS_BROKER_STATE_DISABLED",
		2: "EGRESS_BROKER_STATE_EMBEDDED",
		5: "EGRESS_BROKER_STATE_LOCAL_OK",
		6: "EGRESS_BROKER_STATE_LOCAL_UNREACHABLE",
	}
	EgressBrokerState_value = map[string]int32{
		"EGRESS_BROKER_STATE_UNSPECIFIED":       0,
		"EGRESS_BROKER_STATE_DISABLED":          1,
		"EGRESS_BROKER_STATE_EMBEDDED":          2,
		"EGRESS_BROKER_STATE_LOCAL_OK":          5,
		"EGRESS_BROKER_STATE_LOCAL_UNREACHABLE": 6,
	}
)

func (x EgressBrokerState) Enum() *EgressBrokerState {
	p := new(EgressBrokerState)
	*p = x
	return p
}

func (x EgressBrokerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EgressBrokerState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_scheduler_proto_enumTypes[1].Descriptor()
}

func (EgressBrokerState) Type() protoreflect.EnumType {
	return &file_api_proto_scheduler_proto_enumTypes[1]
}

func (x EgressBrokerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EgressBrokerState.Descriptor instead.
func (EgressBrokerState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{1}
}

type SandboxEventType int32

const (
	SandboxEventType_SANDBOX_EVENT_TYPE_UNSPECIFIED SandboxEventType = 0
	SandboxEventType_SANDBOX_EVENT_TYPE_CREATE      SandboxEventType = 1
	SandboxEventType_SANDBOX_EVENT_TYPE_DELETE      SandboxEventType = 2
	SandboxEventType_SANDBOX_EVENT_TYPE_PAUSE       SandboxEventType = 3
	SandboxEventType_SANDBOX_EVENT_TYPE_RESUME      SandboxEventType = 4
	// Fork events are reported once per child sandbox; sandbox_id and requested
	// resources refer to the child sandbox, not the source sandbox.
	SandboxEventType_SANDBOX_EVENT_TYPE_FORK SandboxEventType = 5
)

// Enum value maps for SandboxEventType.
var (
	SandboxEventType_name = map[int32]string{
		0: "SANDBOX_EVENT_TYPE_UNSPECIFIED",
		1: "SANDBOX_EVENT_TYPE_CREATE",
		2: "SANDBOX_EVENT_TYPE_DELETE",
		3: "SANDBOX_EVENT_TYPE_PAUSE",
		4: "SANDBOX_EVENT_TYPE_RESUME",
		5: "SANDBOX_EVENT_TYPE_FORK",
	}
	SandboxEventType_value = map[string]int32{
		"SANDBOX_EVENT_TYPE_UNSPECIFIED": 0,
		"SANDBOX_EVENT_TYPE_CREATE":      1,
		"SANDBOX_EVENT_TYPE_DELETE":      2,
		"SANDBOX_EVENT_TYPE_PAUSE":       3,
		"SANDBOX_EVENT_TYPE_RESUME":      4,
		"SANDBOX_EVENT_TYPE_FORK":        5,
	}
)

func (x SandboxEventType) Enum() *SandboxEventType {
	p := new(SandboxEventType)
	*p = x
	return p
}

func (x SandboxEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandboxEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_scheduler_proto_enumTypes[2].Descriptor()
}

func (SandboxEventType) Type() protoreflect.EnumType {
	return &file_api_proto_scheduler_proto_enumTypes[2]
}

func (x SandboxEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SandboxEventType.Descriptor instead.
func (SandboxEventType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{2}
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_api_proto_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Node) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

// ScheduleRequestHint carries structured information parsed from the incoming
// request so the scheduler can make a more informed placement decision. Only
// request types that benefit from scheduling hints are represented; other
// requests omit the hint entirely.
type ScheduleRequestHint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ScheduleRequestHint_NewColdSandbox
	//	*ScheduleRequestHint_NewSandbox
	Kind          isScheduleRequestHint_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleRequestHint) Reset() {
	*x = ScheduleRequestHint{}
	mi := &file_api_proto_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRequestHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequestHint) ProtoMessage() {}

func (x *ScheduleRequestHint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRequestHint.ProtoReflect.Descriptor instead.
func (*ScheduleRequestHint) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleRequestHint) GetKind() isScheduleRequestHint_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ScheduleRequestHint) GetNewColdSandbox() *NewColdSandboxHint {
	if x != nil {
		if x, ok := x.Kind.(*ScheduleRequestHint_NewColdSandbox); ok {
			return x.NewColdSandbox
		}
	}
	return nil
}

func (x *ScheduleRequestHint) GetNewSandbox() *NewSandboxHint {
	if x != nil {
		if x, ok := x.Kind.(*ScheduleRequestHint_NewSandbox); ok {
			return x.NewSandbox
		}
	}
	return nil
}

type isScheduleRequestHint_Kind interface {
	isScheduleRequestHint_Kind()
}

type ScheduleRequestHint_NewColdSandbox struct {
	NewColdSandbox *NewColdSandboxHint `protobuf:"bytes,1,opt,name=new_cold_sandbox,json=newColdSandbox,proto3,oneof"`
}

type ScheduleRequestHint_NewSandbox struct {
	NewSandbox *NewSandboxHint `protobuf:"bytes,2,opt,name=new_sandbox,json=newSandbox,proto3,oneof"`
}

func (*ScheduleRequestHint_NewColdSandbox) isScheduleRequestHint_Kind() {}

func (*ScheduleRequestHint_NewSandbox) isScheduleRequestHint_Kind() {}

// NewColdSandboxHint describes a POST /sandboxes-cold request.
type NewColdSandboxHint struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	CpuCount uint32                 `protobuf:"varint,1,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	MemoryMb uint64                 `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	// OCI image references involved in the cold start: the rootfs image plus any
	// attached-drive images.
	Images []string `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	// Sandbox metadata key/value pairs parsed from the request body.
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewColdSandboxHint) Reset() {
	*x = NewColdSandboxHint{}
	mi := &file_api_proto_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewColdSandboxHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewColdSandboxHint) ProtoMessage() {}

func (x *NewColdSandboxHint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewColdSandboxHint.ProtoReflect.Descriptor instead.
func (*NewColdSandboxHint) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *NewColdSandboxHint) GetCpuCount() uint32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *NewColdSandboxHint) GetMemoryMb() uint64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *NewColdSandboxHint) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *NewColdSandboxHint) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// NewSandboxHint describes a POST /sandboxes request.
type NewSandboxHint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sandbox metadata key/value pairs parsed from the request body.
	Metadata map[string]string `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The sandbox's declared size, so placement can weigh the request against
	// what each node has already allocated.
	//
	// Both use proto3 explicit presence, and that is load-bearing rather than
	// stylistic: "the caller did not say" and "the caller said zero" have to
	// be distinguishable. A request for 0 vCPU is a real (if unusual) answer
	// that participates in the arithmetic; an absent field means placement is
	// scoring blind and is counted as such
	// (agentenv_api_placement_missing_request_resources_total). Without
	// presence, a legacy caller and a zero-sized request would be the same
	// bytes on the wire.
	//
	// Additive: older peers ignore both tags, and this build reads an older
	// peer's hint as "not stated". Field 1 is metadata, so these take 2 and 3.
	CpuCount *uint32 `protobuf:"varint,2,opt,name=cpu_count,json=cpuCount,proto3,oneof" json:"cpu_count,omitempty"`
	// MiB, matching SandboxResources::memory_mib, which is where the value
	// comes from. Named for its unit precisely because the cold-start hint
	// above spells the same quantity `memory_mb`.
	MemoryMib *uint64 `protobuf:"varint,3,opt,name=memory_mib,json=memoryMib,proto3,oneof" json:"memory_mib,omitempty"`
	// The node the caller would rather see chosen: where a paused sandbox's
	// bytes were last warm. Honoured only while that node is schedulable;
	// empty means no preference.
	PreferredNodeId string `protobuf:"bytes,4,opt,name=preferred_node_id,json=preferredNodeId,proto3" json:"preferred_node_id,omitempty"`
	// Nodes that already refused this sandbox in this launch, so the retry is
	// placed elsewhere. A preferred node listed here is not preferred.
	ExcludedNodeIds []string `protobuf:"bytes,5,rep,name=excluded_node_ids,json=excludedNodeIds,proto3" json:"excluded_node_ids,omitempty"`
	// The sandbox declares network rules, so only a node whose heartbeat reports
	// a usable egress broker may take it.
	RequiresEgressBroker bool `protobuf:"varint,6,opt,name=requires_egress_broker,json=requiresEgressBroker,proto3" json:"requires_egress_broker,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NewSandboxHint) Reset() {
	*x = NewSandboxHint{}
	mi := &file_api_proto_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewSandboxHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewSandboxHint) ProtoMessage() {}

func (x *NewSandboxHint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewSandboxHint.ProtoReflect.Descriptor instead.
func (*NewSandboxHint) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *NewSandboxHint) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *NewSandboxHint) GetCpuCount() uint32 {
	if x != nil && x.CpuCount != nil {
		return *x.CpuCount
	}
	return 0
}

func (x *NewSandboxHint) GetMemoryMib() uint64 {
	if x != nil && x.MemoryMib != nil {
		return *x.MemoryMib
	}
	return 0
}

func (x *NewSandboxHint) GetPreferredNodeId() string {
	if x != nil {
		return x.PreferredNodeId
	}
	return ""
}

func (x *NewSandboxHint) GetExcludedNodeIds() []string {
	if x != nil {
		return x.ExcludedNodeIds
	}
	return nil
}

func (x *NewSandboxHint) GetRequiresEgressBroker() bool {
	if x != nil {
		return x.RequiresEgressBroker
	}
	return false
}

type ScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hint          *ScheduleRequestHint   `protobuf:"bytes,2,opt,name=hint,proto3" json:"hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleRequest) Reset() {
	*x = ScheduleRequest{}
	mi := &file_api_proto_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequest) ProtoMessage() {}

func (x *ScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRequest.ProtoReflect.Descriptor instead.
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *ScheduleRequest) GetHint() *ScheduleRequestHint {
	if x != nil {
		return x.Hint
	}
	return nil
}

type ScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	mi := &file_api_proto_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *ScheduleResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type MachineInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CpuFamily       string                 `protobuf:"bytes,1,opt,name=cpu_family,json=cpuFamily,proto3" json:"cpu_family,omitempty"`
	CpuModel        string                 `protobuf:"bytes,2,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	CpuModelName    string                 `protobuf:"bytes,3,opt,name=cpu_model_name,json=cpuModelName,proto3" json:"cpu_model_name,omitempty"`
	CpuArchitecture string                 `protobuf:"bytes,4,opt,name=cpu_architecture,json=cpuArchitecture,proto3" json:"cpu_architecture,omitempty"`
	CpuConfigJson   string                 `protobuf:"bytes,5,opt,name=cpu_config_json,json=cpuConfigJson,proto3" json:"cpu_config_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MachineInfo) Reset() {
	*x = MachineInfo{}
	mi := &file_api_proto_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineInfo) ProtoMessage() {}

func (x *MachineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineInfo.ProtoReflect.Descriptor instead.
func (*MachineInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *MachineInfo) GetCpuFamily() string {
	if x != nil {
		return x.CpuFamily
	}
	return ""
}

func (x *MachineInfo) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *MachineInfo) GetCpuModelName() string {
	if x != nil {
		return x.CpuModelName
	}
	return ""
}

func (x *MachineInfo) GetCpuArchitecture() string {
	if x != nil {
		return x.CpuArchitecture
	}
	return ""
}

func (x *MachineInfo) GetCpuConfigJson() string {
	if x != nil {
		return x.CpuConfigJson
	}
	return ""
}

type DiskMetric struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MountPoint     string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Device         string                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	FilesystemType string                 `protobuf:"bytes,3,opt,name=filesystem_type,json=filesystemType,proto3" json:"filesystem_type,omitempty"`
	UsedBytes      uint64                 `protobuf:"varint,4,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	TotalBytes     uint64                 `protobuf:"varint,5,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DiskMetric) Reset() {
	*x = DiskMetric{}
	mi := &file_api_proto_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskMetric) ProtoMessage() {}

func (x *DiskMetric) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskMetric.ProtoReflect.Descriptor instead.
func (*DiskMetric) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *DiskMetric) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskMetric) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskMetric) GetFilesystemType() string {
	if x != nil {
		return x.FilesystemType
	}
	return ""
}

func (x *DiskMetric) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *DiskMetric) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type NodeSnapshot struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Status               NodeStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=scheduler.v1.NodeStatus" json:"status,omitempty"`
	AllocatedCpu         uint32                 `protobuf:"varint,2,opt,name=allocated_cpu,json=allocatedCpu,proto3" json:"allocated_cpu,omitempty"`
	AllocatedMemoryBytes uint64                 `protobuf:"varint,3,opt,name=allocated_memory_bytes,json=allocatedMemoryBytes,proto3" json:"allocated_memory_bytes,omitempty"`
	CpuPercent           uint32                 `protobuf:"varint,4,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	CpuCount             uint32                 `protobuf:"varint,5,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	MemoryUsedBytes      uint64                 `protobuf:"varint,6,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes     uint64                 `protobuf:"varint,7,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	Disks                []*DiskMetric          `protobuf:"bytes,8,rep,name=disks,proto3" json:"disks,omitempty"`
	SandboxCount         uint32                 `protobuf:"varint,9,opt,name=sandbox_count,json=sandboxCount,proto3" json:"sandbox_count,omitempty"`
	SandboxStartingCount uint32                 `protobuf:"varint,10,opt,name=sandbox_starting_count,json=sandboxStartingCount,proto3" json:"sandbox_starting_count,omitempty"`
	CreateSuccesses      uint64                 `protobuf:"varint,11,opt,name=create_successes,json=createSuccesses,proto3" json:"create_successes,omitempty"`
	CreateFails          uint64                 `protobuf:"varint,12,opt,name=create_fails,json=createFails,proto3" json:"create_fails,omitempty"`
	ReportedAtUnixMs     int64                  `protobuf:"varint,13,opt,name=reported_at_unix_ms,json=reportedAtUnixMs,proto3" json:"reported_at_unix_ms,omitempty"`
	// Whether this node can run sandboxes that declare network rules. The api
	// half places such sandboxes only on nodes reporting LOCAL_OK.
	EgressBroker  EgressBrokerState `protobuf:"varint,17,opt,name=egress_broker,json=egressBroker,proto3,enum=scheduler.v1.EgressBrokerState" json:"egress_broker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSnapshot) Reset() {
	*x = NodeSnapshot{}
	mi := &file_api_proto_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSnapshot) ProtoMessage() {}

func (x *NodeSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSnapshot.ProtoReflect.Descriptor instead.
func (*NodeSnapshot) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *NodeSnapshot) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *NodeSnapshot) GetAllocatedCpu() uint32 {
	if x != nil {
		return x.AllocatedCpu
	}
	return 0
}

func (x *NodeSnapshot) GetAllocatedMemoryBytes() uint64 {
	if x != nil {
		return x.AllocatedMemoryBytes
	}
	return 0
}

func (x *NodeSnapshot) GetCpuPercent() uint32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *NodeSnapshot) GetCpuCount() uint32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *NodeSnapshot) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *NodeSnapshot) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *NodeSnapshot) GetDisks() []*DiskMetric {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *NodeSnapshot) GetSandboxCount() uint32 {
	if x != nil {
		return x.SandboxCount
	}
	return 0
}

func (x *NodeSnapshot) GetSandboxStartingCount() uint32 {
	if x != nil {
		return x.SandboxStartingCount
	}
	return 0
}

func (x *NodeSnapshot) GetCreateSuccesses() uint64 {
	if x != nil {
		return x.CreateSuccesses
	}
	return 0
}

func (x *NodeSnapshot) GetCreateFails() uint64 {
	if x != nil {
		return x.CreateFails
	}
	return 0
}

func (x *NodeSnapshot) GetReportedAtUnixMs() int64 {
	if x != nil {
		return x.ReportedAtUnixMs
	}
	return 0
}

func (x *NodeSnapshot) GetEgressBroker() EgressBrokerState {
	if x != nil {
		return x.EgressBroker
	}
	return EgressBrokerState_EGRESS_BROKER_STATE_UNSPECIFIED
}

type P2PEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backend       string                 `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PEndpoint) Reset() {
	*x = P2PEndpoint{}
	mi := &file_api_proto_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PEndpoint) ProtoMessage() {}

func (x *P2PEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PEndpoint.ProtoReflect.Descriptor instead.
func (*P2PEndpoint) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *P2PEndpoint) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *P2PEndpoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ObservedNode struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Endpoint          string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	ClusterId         string                 `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ServiceInstanceId string                 `protobuf:"bytes,4,opt,name=service_instance_id,json=serviceInstanceId,proto3" json:"service_instance_id,omitempty"`
	Version           string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Commit            string                 `protobuf:"bytes,6,opt,name=commit,proto3" json:"commit,omitempty"`
	MachineInfo       *MachineInfo           `protobuf:"bytes,7,opt,name=machine_info,json=machineInfo,proto3" json:"machine_info,omitempty"`
	Snapshot          *NodeSnapshot          `protobuf:"bytes,8,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	LastSeenUnixMs    int64                  `protobuf:"varint,9,opt,name=last_seen_unix_ms,json=lastSeenUnixMs,proto3" json:"last_seen_unix_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ObservedNode) Reset() {
	*x = ObservedNode{}
	mi := &file_api_proto_scheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservedNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservedNode) ProtoMessage() {}

func (x *ObservedNode) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservedNode.ProtoReflect.Descriptor instead.
func (*ObservedNode) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{10}
}

func (x *ObservedNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ObservedNode) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ObservedNode) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ObservedNode) GetServiceInstanceId() string {
	if x != nil {
		return x.ServiceInstanceId
	}
	return ""
}

func (x *ObservedNode) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ObservedNode) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *ObservedNode) GetMachineInfo() *MachineInfo {
	if x != nil {
		return x.MachineInfo
	}
	return nil
}

func (x *ObservedNode) GetSnapshot() *NodeSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *ObservedNode) GetLastSeenUnixMs() int64 {
	if x != nil {
		return x.LastSeenUnixMs
	}
	return 0
}

type HeartbeatRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ClusterId         string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ServiceInstanceId string                 `protobuf:"bytes,3,opt,name=service_instance_id,json=serviceInstanceId,proto3" json:"service_instance_id,omitempty"`
	Version           string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Commit            string                 `protobuf:"bytes,5,opt,name=commit,proto3" json:"commit,omitempty"`
	MachineInfo       *MachineInfo           `protobuf:"bytes,6,opt,name=machine_info,json=machineInfo,proto3" json:"machine_info,omitempty"`
	Snapshot          *NodeSnapshot          `protobuf:"bytes,7,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	P2PEndpoint       *P2PEndpoint           `protobuf:"bytes,9,opt,name=p2p_endpoint,json=p2pEndpoint,proto3" json:"p2p_endpoint,omitempty"`
	// The sandboxes alive on this node, and the incarnation each is running
	// under.
	//
	// A node that reports this reports it in full: empty means "nothing here".
	Roster        []*SandboxRosterEntry `protobuf:"bytes,10,rep,name=roster,proto3" json:"roster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_scheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *HeartbeatRequest) GetServiceInstanceId() string {
	if x != nil {
		return x.ServiceInstanceId
	}
	return ""
}

func (x *HeartbeatRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HeartbeatRequest) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *HeartbeatRequest) GetMachineInfo() *MachineInfo {
	if x != nil {
		return x.MachineInfo
	}
	return nil
}

func (x *HeartbeatRequest) GetSnapshot() *NodeSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *HeartbeatRequest) GetP2PEndpoint() *P2PEndpoint {
	if x != nil {
		return x.P2PEndpoint
	}
	return nil
}

func (x *HeartbeatRequest) GetRoster() []*SandboxRosterEntry {
	if x != nil {
		return x.Roster
	}
	return nil
}

// SandboxRosterEntry is one sandbox on a node, as that node reports it.
type SandboxRosterEntry struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SandboxId string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// Lowercase canonical UUIDv7. Empty means this entry takes no part in
	// binding arbitration — it is unknown, so it may install a binding where
	// there is none but may never displace one that names an incarnation.
	//
	// 🔴 Empty does not mean "drop the entry": the entry still routes. Dropping
	// it would trade away a working route to avoid an unprotected one.
	ExecutionId string `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// How long this sandbox's routing projection should live, in whole seconds,
	// as computed by this node. This is the repair path for the same number
	// the api half's own projection writes carry: a write that was lost gets
	// reinstalled by heartbeat reconciliation, and it must be reinstalled with
	// the sandbox's real budget rather than with the receiver's default.
	//
	// 🔴 <= 0 means "use the receiver's binding_ttl", never "never expires".
	// Absent (an older node) lands on the same fallback, which is exactly the
	// behaviour that shipped before this field existed.
	ProjectionTtlSecs uint32 `protobuf:"varint,3,opt,name=projection_ttl_secs,json=projectionTtlSecs,proto3" json:"projection_ttl_secs,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SandboxRosterEntry) Reset() {
	*x = SandboxRosterEntry{}
	mi := &file_api_proto_scheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxRosterEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxRosterEntry) ProtoMessage() {}

func (x *SandboxRosterEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxRosterEntry.ProtoReflect.Descriptor instead.
func (*SandboxRosterEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{12}
}

func (x *SandboxRosterEntry) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxRosterEntry) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *SandboxRosterEntry) GetProjectionTtlSecs() uint32 {
	if x != nil {
		return x.ProjectionTtlSecs
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuConfigJson string                 `protobuf:"bytes,1,opt,name=cpu_config_json,json=cpuConfigJson,proto3" json:"cpu_config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_scheduler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{13}
}

func (x *HeartbeatResponse) GetCpuConfigJson() string {
	if x != nil {
		return x.CpuConfigJson
	}
	return ""
}

type SandboxEvent struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SandboxId            string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	EventType            SandboxEventType       `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=scheduler.v1.SandboxEventType" json:"event_type,omitempty"`
	RequestedCpu         uint32                 `protobuf:"varint,3,opt,name=requested_cpu,json=requestedCpu,proto3" json:"requested_cpu,omitempty"`
	RequestedMemoryBytes uint64                 `protobuf:"varint,4,opt,name=requested_memory_bytes,json=requestedMemoryBytes,proto3" json:"requested_memory_bytes,omitempty"`
	RequestedDiskBytes   uint64                 `protobuf:"varint,5,opt,name=requested_disk_bytes,json=requestedDiskBytes,proto3" json:"requested_disk_bytes,omitempty"`
	// The incarnation this event belongs to. A projection delete must be guarded
	// by it: a pause event that arrives late, for a sandbox id that has since
	// been started again elsewhere under a new incarnation, would otherwise tear
	// down the live record.
	//
	// Empty means the reporter is too old to name one, and the event therefore
	// takes no part in the guard — the receiver ignores it for deletes rather
	// than deleting without a guard.
	ExecutionId   string `protobuf:"bytes,6,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxEvent) Reset() {
	*x = SandboxEvent{}
	mi := &file_api_proto_scheduler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxEvent) ProtoMessage() {}

func (x *SandboxEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxEvent.ProtoReflect.Descriptor instead.
func (*SandboxEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{14}
}

func (x *SandboxEvent) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxEvent) GetEventType() SandboxEventType {
	if x != nil {
		return x.EventType
	}
	return SandboxEventType_SANDBOX_EVENT_TYPE_UNSPECIFIED
}

func (x *SandboxEvent) GetRequestedCpu() uint32 {
	if x != nil {
		return x.RequestedCpu
	}
	return 0
}

func (x *SandboxEvent) GetRequestedMemoryBytes() uint64 {
	if x != nil {
		return x.RequestedMemoryBytes
	}
	return 0
}

func (x *SandboxEvent) GetRequestedDiskBytes() uint64 {
	if x != nil {
		return x.RequestedDiskBytes
	}
	return 0
}

func (x *SandboxEvent) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type ReportSandboxEventRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ClusterId         string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ServiceInstanceId string                 `protobuf:"bytes,3,opt,name=service_instance_id,json=serviceInstanceId,proto3" json:"service_instance_id,omitempty"`
	Events            []*SandboxEvent        `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReportSandboxEventRequest) Reset() {
	*x = ReportSandboxEventRequest{}
	mi := &file_api_proto_scheduler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSandboxEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSandboxEventRequest) ProtoMessage() {}

func (x *ReportSandboxEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSandboxEventRequest.ProtoReflect.Descriptor instead.
func (*ReportSandboxEventRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{15}
}

func (x *ReportSandboxEventRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportSandboxEventRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ReportSandboxEventRequest) GetServiceInstanceId() string {
	if x != nil {
		return x.ServiceInstanceId
	}
	return ""
}

func (x *ReportSandboxEventRequest) GetEvents() []*SandboxEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ReportSandboxEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSandboxEventResponse) Reset() {
	*x = ReportSandboxEventResponse{}
	mi := &file_api_proto_scheduler_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSandboxEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSandboxEventResponse) ProtoMessage() {}

func (x *ReportSandboxEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSandboxEventResponse.ProtoReflect.Descriptor instead.
func (*ReportSandboxEventResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{16}
}

type P2PPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Endpoint      *P2PEndpoint           `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PPeer) Reset() {
	*x = P2PPeer{}
	mi := &file_api_proto_scheduler_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PPeer) ProtoMessage() {}

func (x *P2PPeer) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PPeer.ProtoReflect.Descriptor instead.
func (*P2PPeer) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{17}
}

func (x *P2PPeer) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *P2PPeer) GetEndpoint() *P2PEndpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

type ListP2PPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Backend       string                 `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	ExcludeNodeId string                 `protobuf:"bytes,3,opt,name=exclude_node_id,json=excludeNodeId,proto3" json:"exclude_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListP2PPeersRequest) Reset() {
	*x = ListP2PPeersRequest{}
	mi := &file_api_proto_scheduler_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListP2PPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListP2PPeersRequest) ProtoMessage() {}

func (x *ListP2PPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListP2PPeersRequest.ProtoReflect.Descriptor instead.
func (*ListP2PPeersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{18}
}

func (x *ListP2PPeersRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ListP2PPeersRequest) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *ListP2PPeersRequest) GetExcludeNodeId() string {
	if x != nil {
		return x.ExcludeNodeId
	}
	return ""
}

type ListP2PPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*P2PPeer             `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListP2PPeersResponse) Reset() {
	*x = ListP2PPeersResponse{}
	mi := &file_api_proto_scheduler_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListP2PPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListP2PPeersResponse) ProtoMessage() {}

func (x *ListP2PPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListP2PPeersResponse.ProtoReflect.Descriptor instead.
func (*ListP2PPeersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{19}
}

func (x *ListP2PPeersResponse) GetPeers() []*P2PPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type RecordP2PArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Backend       string                 `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordP2PArtifactRequest) Reset() {
	*x = RecordP2PArtifactRequest{}
	mi := &file_api_proto_scheduler_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordP2PArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordP2PArtifactRequest) ProtoMessage() {}

func (x *RecordP2PArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordP2PArtifactRequest.ProtoReflect.Descriptor instead.
func (*RecordP2PArtifactRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{20}
}

func (x *RecordP2PArtifactRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RecordP2PArtifactRequest) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *RecordP2PArtifactRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RecordP2PArtifactRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RecordP2PArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordP2PArtifactResponse) Reset() {
	*x = RecordP2PArtifactResponse{}
	mi := &file_api_proto_scheduler_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordP2PArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordP2PArtifactResponse) ProtoMessage() {}

func (x *RecordP2PArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordP2PArtifactResponse.ProtoReflect.Descriptor instead.
func (*RecordP2PArtifactResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{21}
}

type ForgetP2PArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Backend       string                 `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetP2PArtifactRequest) Reset() {
	*x = ForgetP2PArtifactRequest{}
	mi := &file_api_proto_scheduler_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetP2PArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetP2PArtifactRequest) ProtoMessage() {}

func (x *ForgetP2PArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetP2PArtifactRequest.ProtoReflect.Descriptor instead.
func (*ForgetP2PArtifactRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{22}
}

func (x *ForgetP2PArtifactRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ForgetP2PArtifactRequest) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *ForgetP2PArtifactRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ForgetP2PArtifactRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ForgetP2PArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetP2PArtifactResponse) Reset() {
	*x = ForgetP2PArtifactResponse{}
	mi := &file_api_proto_scheduler_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetP2PArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetP2PArtifactResponse) ProtoMessage() {}

func (x *ForgetP2PArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetP2PArtifactResponse.ProtoReflect.Descriptor instead.
func (*ForgetP2PArtifactResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{23}
}

type LookupP2PArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Backend       string                 `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	ExcludeNodeId string                 `protobuf:"bytes,4,opt,name=exclude_node_id,json=excludeNodeId,proto3" json:"exclude_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupP2PArtifactRequest) Reset() {
	*x = LookupP2PArtifactRequest{}
	mi := &file_api_proto_scheduler_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupP2PArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupP2PArtifactRequest) ProtoMessage() {}

func (x *LookupP2PArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupP2PArtifactRequest.ProtoReflect.Descriptor instead.
func (*LookupP2PArtifactRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{24}
}

func (x *LookupP2PArtifactRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *LookupP2PArtifactRequest) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *LookupP2PArtifactRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LookupP2PArtifactRequest) GetExcludeNodeId() string {
	if x != nil {
		return x.ExcludeNodeId
	}
	return ""
}

type LookupP2PArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*P2PPeer             `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupP2PArtifactResponse) Reset() {
	*x = LookupP2PArtifactResponse{}
	mi := &file_api_proto_scheduler_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupP2PArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupP2PArtifactResponse) ProtoMessage() {}

func (x *LookupP2PArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupP2PArtifactResponse.ProtoReflect.Descriptor instead.
func (*LookupP2PArtifactResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{25}
}

func (x *LookupP2PArtifactResponse) GetPeers() []*P2PPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_api_proto_scheduler_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{26}
}

func (x *GetNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetNodeRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type GetNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *ObservedNode          `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeResponse) Reset() {
	*x = GetNodeResponse{}
	mi := &file_api_proto_scheduler_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeResponse) ProtoMessage() {}

func (x *GetNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeResponse.ProtoReflect.Descriptor instead.
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{27}
}

func (x *GetNodeResponse) GetNode() *ObservedNode {
	if x != nil {
		return x.Node
	}
	return nil
}

type UnregisterNodeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ServiceInstanceId string                 `protobuf:"bytes,2,opt,name=service_instance_id,json=serviceInstanceId,proto3" json:"service_instance_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UnregisterNodeRequest) Reset() {
	*x = UnregisterNodeRequest{}
	mi := &file_api_proto_scheduler_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterNodeRequest) ProtoMessage() {}

func (x *UnregisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterNodeRequest.ProtoReflect.Descriptor instead.
func (*UnregisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{28}
}

func (x *UnregisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UnregisterNodeRequest) GetServiceInstanceId() string {
	if x != nil {
		return x.ServiceInstanceId
	}
	return ""
}

type UnregisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterNodeResponse) Reset() {
	*x = UnregisterNodeResponse{}
	mi := &file_api_proto_scheduler_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterNodeResponse) ProtoMessage() {}

func (x *UnregisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterNodeResponse.ProtoReflect.Descriptor instead.
func (*UnregisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{29}
}

var File_api_proto_scheduler_proto protoreflect.FileDescriptor

const file_api_proto_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/scheduler.proto\x12\fscheduler.v1\";\n" +
	"\x04Node\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\"\xac\x01\n" +
	"\x13ScheduleRequestHint\x12L\n" +
	"\x10new_cold_sandbox\x18\x01 \x01(\v2 .scheduler.v1.NewColdSandboxHintH\x00R\x0enewColdSandbox\x12?\n" +
	"\vnew_sandbox\x18\x02 \x01(\v2\x1c.scheduler.v1.NewSandboxHintH\x00R\n" +
	"newSandboxB\x06\n" +
	"\x04kind\"\xef\x01\n" +
	"\x12NewColdSandboxHint\x12\x1b\n" +
	"\tcpu_count\x18\x01 \x01(\rR\bcpuCount\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x04R\bmemoryMb\x12\x16\n" +
	"\x06images\x18\x03 \x03(\tR\x06images\x12J\n" +
	"\bmetadata\x18\x04 \x03(\v2..scheduler.v1.NewColdSandboxHint.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x03\n" +
	"\x0eNewSandboxHint\x12F\n" +
	"\bmetadata\x18\x01 \x03(\v2*.scheduler.v1.NewSandboxHint.MetadataEntryR\bmetadata\x12 \n" +
	"\tcpu_count\x18\x02 \x01(\rH\x00R\bcpuCount\x88\x01\x01\x12\"\n" +
	"\n" +
	"memory_mib\x18\x03 \x01(\x04H\x01R\tmemoryMib\x88\x01\x01\x12*\n" +
	"\x11preferred_node_id\x18\x04 \x01(\tR\x0fpreferredNodeId\x12*\n" +
	"\x11excluded_node_ids\x18\x05 \x03(\tR\x0fexcludedNodeIds\x124\n" +
	"\x16requires_egress_broker\x18\x06 \x01(\bR\x14requiresEgressBroker\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_cpu_countB\r\n" +
	"\v_memory_mib\"N\n" +
	"\x0fScheduleRequest\x125\n" +
	"\x04hint\x18\x02 \x01(\v2!.scheduler.v1.ScheduleRequestHintR\x04hintJ\x04\b\x01\x10\x02\":\n" +
	"\x10ScheduleResponse\x12&\n" +
	"\x04node\x18\x01 \x01(\v2\x12.scheduler.v1.NodeR\x04node\"\xc2\x01\n" +
	"\vMachineInfo\x12\x1d\n" +
	"\n" +
	"cpu_family\x18\x01 \x01(\tR\tcpuFamily\x12\x1b\n" +
	"\tcpu_model\x18\x02 \x01(\tR\bcpuModel\x12$\n" +
	"\x0ecpu_model_name\x18\x03 \x01(\tR\fcpuModelName\x12)\n" +
	"\x10cpu_architecture\x18\x04 \x01(\tR\x0fcpuArchitecture\x12&\n" +
	"\x0fcpu_config_json\x18\x05 \x01(\tR\rcpuConfigJson\"\xae\x01\n" +
	"\n" +
	"DiskMetric\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12'\n" +
	"\x0ffilesystem_type\x18\x03 \x01(\tR\x0efilesystemType\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x04 \x01(\x04R\tusedBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x05 \x01(\x04R\n" +
	"totalBytes\"\xde\x05\n" +
	"\fNodeSnapshot\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.scheduler.v1.NodeStatusR\x06status\x12#\n" +
	"\rallocated_cpu\x18\x02 \x01(\rR\fallocatedCpu\x124\n" +
	"\x16allocated_memory_bytes\x18\x03 \x01(\x04R\x14allocatedMemoryBytes\x12\x1f\n" +
	"\vcpu_percent\x18\x04 \x01(\rR\n" +
	"cpuPercent\x12\x1b\n" +
	"\tcpu_count\x18\x05 \x01(\rR\bcpuCount\x12*\n" +
	"\x11memory_used_bytes\x18\x06 \x01(\x04R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\a \x01(\x04R\x10memoryTotalBytes\x12.\n" +
	"\x05disks\x18\b \x03(\v2\x18.scheduler.v1.DiskMetricR\x05disks\x12#\n" +
	"\rsandbox_count\x18\t \x01(\rR\fsandboxCount\x124\n" +
	"\x16sandbox_starting_count\x18\n" +
	" \x01(\rR\x14sandboxStartingCount\x12)\n" +
	"\x10create_successes\x18\v \x01(\x04R\x0fcreateSuccesses\x12!\n" +
	"\fcreate_fails\x18\f \x01(\x04R\vcreateFails\x12-\n" +
	"\x13reported_at_unix_ms\x18\r \x01(\x03R\x10reportedAtUnixMs\x12D\n" +
	"\regress_broker\x18\x11 \x01(\x0e2\x1f.scheduler.v1.EgressBrokerStateR\fegressBrokerJ\x04\b\x0e\x10\x0fJ\x04\b\x0f\x10\x10J\x04\b\x10\x10\x11R\x14paused_sandbox_countR\x14paused_allocated_cpuR\x1dpaused_allocated_memory_bytes\"A\n" +
	"\vP2pEndpoint\x12\x18\n" +
	"\abackend\x18\x01 \x01(\tR\abackend\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\xe5\x02\n" +
	"\fObservedNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x12.\n" +
	"\x13service_instance_id\x18\x04 \x01(\tR\x11serviceInstanceId\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x06 \x01(\tR\x06commit\x12<\n" +
	"\fmachine_info\x18\a \x01(\v2\x19.scheduler.v1.MachineInfoR\vmachineInfo\x126\n" +
	"\bsnapshot\x18\b \x01(\v2\x1a.scheduler.v1.NodeSnapshotR\bsnapshot\x12)\n" +
	"\x11last_seen_unix_ms\x18\t \x01(\x03R\x0elastSeenUnixMs\"\xad\x03\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12.\n" +
	"\x13service_instance_id\x18\x03 \x01(\tR\x11serviceInstanceId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x05 \x01(\tR\x06commit\x12<\n" +
	"\fmachine_info\x18\x06 \x01(\v2\x19.scheduler.v1.MachineInfoR\vmachineInfo\x126\n" +
	"\bsnapshot\x18\a \x01(\v2\x1a.scheduler.v1.NodeSnapshotR\bsnapshot\x12<\n" +
	"\fp2p_endpoint\x18\t \x01(\v2\x19.scheduler.v1.P2pEndpointR\vp2pEndpoint\x128\n" +
	"\x06roster\x18\n" +
	" \x03(\v2 .scheduler.v1.SandboxRosterEntryR\x06rosterJ\x04\b\b\x10\tR\vsandbox_ids\"\x94\x01\n" +
	"\x12SandboxRosterEntry\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12.\n" +
	"\x13projection_ttl_secs\x18\x03 \x01(\rR\x11projectionTtlSecsJ\x04\b\x04\x10\x05R\x06paused\"W\n" +
	"\x11HeartbeatResponse\x12&\n" +
	"\x0fcpu_config_json\x18\x01 \x01(\tR\rcpuConfigJsonJ\x04\b\x02\x10\x03R\x14disowned_sandbox_ids\"\x9c\x02\n" +
	"\fSandboxEvent\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12=\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2\x1e.scheduler.v1.SandboxEventTypeR\teventType\x12#\n" +
	"\rrequested_cpu\x18\x03 \x01(\rR\frequestedCpu\x124\n" +
	"\x16requested_memory_bytes\x18\x04 \x01(\x04R\x14requestedMemoryBytes\x120\n" +
	"\x14requested_disk_bytes\x18\x05 \x01(\x04R\x12requestedDiskBytes\x12!\n" +
	"\fexecution_id\x18\x06 \x01(\tR\vexecutionId\"\xb7\x01\n" +
	"\x19ReportSandboxEventRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12.\n" +
	"\x13service_instance_id\x18\x03 \x01(\tR\x11serviceInstanceId\x122\n" +
	"\x06events\x18\x04 \x03(\v2\x1a.scheduler.v1.SandboxEventR\x06events\"\x1c\n" +
	"\x1aReportSandboxEventResponse\"Y\n" +
	"\aP2pPeer\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x125\n" +
	"\bendpoint\x18\x02 \x01(\v2\x19.scheduler.v1.P2pEndpointR\bendpoint\"v\n" +
	"\x13ListP2pPeersRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\x12&\n" +
	"\x0fexclude_node_id\x18\x03 \x01(\tR\rexcludeNodeId\"C\n" +
	"\x14ListP2pPeersResponse\x12+\n" +
	"\x05peers\x18\x01 \x03(\v2\x15.scheduler.v1.P2pPeerR\x05peers\"~\n" +
	"\x18RecordP2pArtifactRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\"\x1b\n" +
	"\x19RecordP2pArtifactResponse\"~\n" +
	"\x18ForgetP2pArtifactRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\"\x1b\n" +
	"\x19ForgetP2pArtifactResponse\"\x8d\x01\n" +
	"\x18LookupP2pArtifactRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12&\n" +
	"\x0fexclude_node_id\x18\x04 \x01(\tR\rexcludeNodeId\"H\n" +
	"\x19LookupP2pArtifactResponse\x12+\n" +
	"\x05peers\x18\x01 \x03(\v2\x15.scheduler.v1.P2pPeerR\x05peers\"H\n" +
	"\x0eGetNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\"A\n" +
	"\x0fGetNodeResponse\x12.\n" +
	"\x04node\x18\x01 \x01(\v2\x1a.scheduler.v1.ObservedNodeR\x04node\"`\n" +
	"\x15UnregisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12.\n" +
	"\x13service_instance_id\x18\x02 \x01(\tR\x11serviceInstanceId\"\x18\n" +
	"\x16UnregisterNodeResponse*\xac\x01\n" +
	"\n" +
	"NodeStatus\x12\x1b\n" +
	"\x17NODE_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11NODE_STATUS_READY\x10\x01\x12\x1a\n" +
	"\x16NODE_STATUS_CONNECTING\x10\x02\x12\x19\n" +
	"\x15NODE_STATUS_UNHEALTHY\x10\x03\x12\x19\n" +
	"\x15NODE_STATUS_LINGERING\x10\x04\x12\x18\n" +
	"\x14NODE_STATUS_DRAINING\x10\x05*\x9c\x02\n" +
	"\x11EgressBrokerState\x12#\n" +
	"\x1fEGRESS_BROKER_STATE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cEGRESS_BROKER_STATE_DISABLED\x10\x01\x12 \n" +
	"\x1cEGRESS_BROKER_STATE_EMBEDDED\x10\x02\x12 \n" +
	"\x1cEGRESS_BROKER_STATE_LOCAL_OK\x10\x05\x12)\n" +
	"%EGRESS_BROKER_STATE_LOCAL_UNREACHABLE\x10\x06\"\x04\b\x03\x10\x03\"\x04\b\x04\x10\x04*\x1dEGRESS_BROKER_STATE_REMOTE_OK*&EGRESS_BROKER_STATE_REMOTE_UNREACHABLE*\xce\x01\n" +
	"\x10SandboxEventType\x12\"\n" +
	"\x1eSANDBOX_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19SANDBOX_EVENT_TYPE_CREATE\x10\x01\x12\x1d\n" +
	"\x19SANDBOX_EVENT_TYPE_DELETE\x10\x02\x12\x1c\n" +
	"\x18SANDBOX_EVENT_TYPE_PAUSE\x10\x03\x12\x1d\n" +
	"\x19SANDBOX_EVENT_TYPE_RESUME\x10\x04\x12\x1b\n" +
	"\x17SANDBOX_EVENT_TYPE_FORK\x10\x052\xbb\x06\n" +
	"\tScheduler\x12I\n" +
	"\bSchedule\x12\x1d.scheduler.v1.ScheduleRequest\x1a\x1e.scheduler.v1.ScheduleResponse\x12L\n" +
	"\tHeartbeat\x12\x1e.scheduler.v1.HeartbeatRequest\x1a\x1f.scheduler.v1.HeartbeatResponse\x12g\n" +
	"\x12ReportSandboxEvent\x12'.scheduler.v1.ReportSandboxEventRequest\x1a(.scheduler.v1.ReportSandboxEventResponse\x12U\n" +
	"\fListP2pPeers\x12!.scheduler.v1.ListP2pPeersRequest\x1a\".scheduler.v1.ListP2pPeersResponse\x12d\n" +
	"\x11RecordP2pArtifact\x12&.scheduler.v1.RecordP2pArtifactRequest\x1a'.scheduler.v1.RecordP2pArtifactResponse\x12d\n" +
	"\x11ForgetP2pArtifact\x12&.scheduler.v1.ForgetP2pArtifactRequest\x1a'.scheduler.v1.ForgetP2pArtifactResponse\x12d\n" +
	"\x11LookupP2pArtifact\x12&.scheduler.v1.LookupP2pArtifactRequest\x1a'.scheduler.v1.LookupP2pArtifactResponse\x12F\n" +
	"\aGetNode\x12\x1c.scheduler.v1.GetNodeRequest\x1a\x1d.scheduler.v1.GetNodeResponse\x12[\n" +
	"\x0eUnregisterNode\x12#.scheduler.v1.UnregisterNodeRequest\x1a$.scheduler.v1.UnregisterNodeResponseB)Z'agentenv/services/api/proto;schedulerv1b\x06proto3"

var (
	file_api_proto_scheduler_proto_rawDescOnce sync.Once
	file_api_proto_scheduler_proto_rawDescData []byte
)

func file_api_proto_scheduler_proto_rawDescGZIP() []byte {
	file_api_proto_scheduler_proto_rawDescOnce.Do(func() {
		file_api_proto_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_scheduler_proto_rawDesc), len(file_api_proto_scheduler_proto_rawDesc)))
	})
	return file_api_proto_scheduler_proto_rawDescData
}

var file_api_proto_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_api_proto_scheduler_proto_goTypes = []any{
	(NodeStatus)(0),                    // 0: scheduler.v1.NodeStatus
	(EgressBrokerState)(0),             // 1: scheduler.v1.EgressBrokerState
	(SandboxEventType)(0),              // 2: scheduler.v1.SandboxEventType
	(*Node)(nil),                       // 3: scheduler.v1.Node
	(*ScheduleRequestHint)(nil),        // 4: scheduler.v1.ScheduleRequestHint
	(*NewColdSandboxHint)(nil),         // 5: scheduler.v1.NewColdSandboxHint
	(*NewSandboxHint)(nil),             // 6: scheduler.v1.NewSandboxHint
	(*ScheduleRequest)(nil),            // 7: scheduler.v1.ScheduleRequest
	(*ScheduleResponse)(nil),           // 8: scheduler.v1.ScheduleResponse
	(*MachineInfo)(nil),                // 9: scheduler.v1.MachineInfo
	(*DiskMetric)(nil),                 // 10: scheduler.v1.DiskMetric
	(*NodeSnapshot)(nil),               // 11: scheduler.v1.NodeSnapshot
	(*P2PEndpoint)(nil),                // 12: scheduler.v1.P2pEndpoint
	(*ObservedNode)(nil),               // 13: scheduler.v1.ObservedNode
	(*HeartbeatRequest)(nil),           // 14: scheduler.v1.HeartbeatRequest
	(*SandboxRosterEntry)(nil),         // 15: scheduler.v1.SandboxRosterEntry
	(*HeartbeatResponse)(nil),          // 16: scheduler.v1.HeartbeatResponse
	(*SandboxEvent)(nil),               // 17: scheduler.v1.SandboxEvent
	(*ReportSandboxEventRequest)(nil),  // 18: scheduler.v1.ReportSandboxEventRequest
	(*ReportSandboxEventResponse)(nil), // 19: scheduler.v1.ReportSandboxEventResponse
	(*P2PPeer)(nil),                    // 20: scheduler.v1.P2pPeer
	(*ListP2PPeersRequest)(nil),        // 21: scheduler.v1.ListP2pPeersRequest
	(*ListP2PPeersResponse)(nil),       // 22: scheduler.v1.ListP2pPeersResponse
	(*RecordP2PArtifactRequest)(nil),   // 23: scheduler.v1.RecordP2pArtifactRequest
	(*RecordP2PArtifactResponse)(nil),  // 24: scheduler.v1.RecordP2pArtifactResponse
	(*ForgetP2PArtifactRequest)(nil),   // 25: scheduler.v1.ForgetP2pArtifactRequest
	(*ForgetP2PArtifactResponse)(nil),  // 26: scheduler.v1.ForgetP2pArtifactResponse
	(*LookupP2PArtifactRequest)(nil),   // 27: scheduler.v1.LookupP2pArtifactRequest
	(*LookupP2PArtifactResponse)(nil),  // 28: scheduler.v1.LookupP2pArtifactResponse
	(*GetNodeRequest)(nil),             // 29: scheduler.v1.GetNodeRequest
	(*GetNodeResponse)(nil),            // 30: scheduler.v1.GetNodeResponse
	(*UnregisterNodeRequest)(nil),      // 31: scheduler.v1.UnregisterNodeRequest
	(*UnregisterNodeResponse)(nil),     // 32: scheduler.v1.UnregisterNodeResponse
	nil,                                // 33: scheduler.v1.NewColdSandboxHint.MetadataEntry
	nil,                                // 34: scheduler.v1.NewSandboxHint.MetadataEntry
}
var file_api_proto_scheduler_proto_depIdxs = []int32{
	5,  // 0: scheduler.v1.ScheduleRequestHint.new_cold_sandbox:type_name -> scheduler.v1.NewColdSandboxHint
	6,  // 1: scheduler.v1.ScheduleRequestHint.new_sandbox:type_name -> scheduler.v1.NewSandboxHint
	33, // 2: scheduler.v1.NewColdSandboxHint.metadata:type_name -> scheduler.v1.NewColdSandboxHint.MetadataEntry
	34, // 3: scheduler.v1.NewSandboxHint.metadata:type_name -> scheduler.v1.NewSandboxHint.MetadataEntry
	4,  // 4: scheduler.v1.ScheduleRequest.hint:type_name -> scheduler.v1.ScheduleRequestHint
	3,  // 5: scheduler.v1.ScheduleResponse.node:type_name -> scheduler.v1.Node
	0,  // 6: scheduler.v1.NodeSnapshot.status:type_name -> scheduler.v1.NodeStatus
	10, // 7: scheduler.v1.NodeSnapshot.disks:type_name -> scheduler.v1.DiskMetric
	1,  // 8: scheduler.v1.NodeSnapshot.egress_broker:type_name -> scheduler.v1.EgressBrokerState
	9,  // 9: scheduler.v1.ObservedNode.machine_info:type_name -> scheduler.v1.MachineInfo
	11, // 10: scheduler.v1.ObservedNode.snapshot:type_name -> scheduler.v1.NodeSnapshot
	9,  // 11: scheduler.v1.HeartbeatRequest.machine_info:type_name -> scheduler.v1.MachineInfo
	11, // 12: scheduler.v1.HeartbeatRequest.snapshot:type_name -> scheduler.v1.NodeSnapshot
	12, // 13: scheduler.v1.HeartbeatRequest.p2p_endpoint:type_name -> scheduler.v1.P2pEndpoint
	15, // 14: scheduler.v1.HeartbeatRequest.roster:type_name -> scheduler.v1.SandboxRosterEntry
	2,  // 15: scheduler.v1.SandboxEvent.event_type:type_name -> scheduler.v1.SandboxEventType
	17, // 16: scheduler.v1.ReportSandboxEventRequest.events:type_name -> scheduler.v1.SandboxEvent
	12, // 17: scheduler.v1.P2pPeer.endpoint:type_name -> scheduler.v1.P2pEndpoint
	20, // 18: scheduler.v1.ListP2pPeersResponse.peers:type_name -> scheduler.v1.P2pPeer
	20, // 19: scheduler.v1.LookupP2pArtifactResponse.peers:type_name -> scheduler.v1.P2pPeer
	13, // 20: scheduler.v1.GetNodeResponse.node:type_name -> scheduler.v1.ObservedNode
	7,  // 21: scheduler.v1.Scheduler.Schedule:input_type -> scheduler.v1.ScheduleRequest
	14, // 22: scheduler.v1.Scheduler.Heartbeat:input_type -> scheduler.v1.HeartbeatRequest
	18, // 23: scheduler.v1.Scheduler.ReportSandboxEvent:input_type -> scheduler.v1.ReportSandboxEventRequest
	21, // 24: scheduler.v1.Scheduler.ListP2pPeers:input_type -> scheduler.v1.ListP2pPeersRequest
	23, // 25: scheduler.v1.Scheduler.RecordP2pArtifact:input_type -> scheduler.v1.RecordP2pArtifactRequest
	25, // 26: scheduler.v1.Scheduler.ForgetP2pArtifact:input_type -> scheduler.v1.ForgetP2pArtifactRequest
	27, // 27: scheduler.v1.Scheduler.LookupP2pArtifact:input_type -> scheduler.v1.LookupP2pArtifactRequest
	29, // 28: scheduler.v1.Scheduler.GetNode:input_type -> scheduler.v1.GetNodeRequest
	31, // 29: scheduler.v1.Scheduler.UnregisterNode:input_type -> scheduler.v1.UnregisterNodeRequest
	8,  // 30: scheduler.v1.Scheduler.Schedule:output_type -> scheduler.v1.ScheduleResponse
	16, // 31: scheduler.v1.Scheduler.Heartbeat:output_type -> scheduler.v1.HeartbeatResponse
	19, // 32: scheduler.v1.Scheduler.ReportSandboxEvent:output_type -> scheduler.v1.ReportSandboxEventResponse
	22, // 33: scheduler.v1.Scheduler.ListP2pPeers:output_type -> scheduler.v1.ListP2pPeersResponse
	24, // 34: scheduler.v1.Scheduler.RecordP2pArtifact:output_type -> scheduler.v1.RecordP2pArtifactResponse
	26, // 35: scheduler.v1.Scheduler.ForgetP2pArtifact:output_type -> scheduler.v1.ForgetP2pArtifactResponse
	28, // 36: scheduler.v1.Scheduler.LookupP2pArtifact:output_type -> scheduler.v1.LookupP2pArtifactResponse
	30, // 37: scheduler.v1.Scheduler.GetNode:output_type -> scheduler.v1.GetNodeResponse
	32, // 38: scheduler.v1.Scheduler.UnregisterNode:output_type -> scheduler.v1.UnregisterNodeResponse
	30, // [30:39] is the sub-list for method output_type
	21, // [21:30] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_api_proto_scheduler_proto_init() }
func file_api_proto_scheduler_proto_init() {
	if File_api_proto_scheduler_proto != nil {
		return
	}
	file_api_proto_scheduler_proto_msgTypes[1].OneofWrappers = []any{
		(*ScheduleRequestHint_NewColdSandbox)(nil),
		(*ScheduleRequestHint_NewSandbox)(nil),
	}
	file_api_proto_scheduler_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_scheduler_proto_rawDesc), len(file_api_proto_scheduler_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_scheduler_proto_goTypes,
		DependencyIndexes: file_api_proto_scheduler_proto_depIdxs,
		EnumInfos:         file_api_proto_scheduler_proto_enumTypes,
		MessageInfos:      file_api_proto_scheduler_proto_msgTypes,
	}.Build()
	File_api_proto_scheduler_proto = out.File
	file_api_proto_scheduler_proto_goTypes = nil
	file_api_proto_scheduler_proto_depIdxs = nil
}
